### ISSUE TITLE
Doc: How to backup and restore a custom PostgreSQL database

### ISSUE THREAD

**Issue by vijay-dcrust** [stashed/stash#1002]
**Backup**
      Stashing the Custom Postgres Installation can fail due to db authentication problem if the Secret do not contain the keyword `POSTGRES_USER` and `POSTGRES_PASSWORD` to store the db username and password respectively. If that is the case, you need to create a secret manually using the username and password and update the same in `AppBinding`. Below is an example of secret generated automatically from a custom Postgres installation.

```yaml
apiVersion: v1
data:
  password: abcdefghijklmn==
  username: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: "2019-04-10T13:39:46Z"
  labels:
    application: spilo
    team: acid
    version: acid-db
  name: postgres.acid.credentials
  namespace: demo
  resourceVersion: "2846094"
  selfLink: /api/v1/namespaces/infra/secrets/postgres.acid.credentials
  uid: 1b0b17f4-5b96-11e9-a6c7-b026285089d8
type: Opaque
```

Using the DB credential automatically generated by custom postgres installation, a new secret should be created using the below simple yaml and update the same in `AppBinding`.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credential
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: abcdefghijklmn==
```

**Restore**
     During the restore , you have to use the same postgres password as used during the backup, otherwise the restore would fail giving the authentication error. So Restore `AppBinding` should be updated accordingly.

**Comment by k0da** [comment]
It would be nice if AppBinding spec can be extended with secret.userkey and secret.passwordkey in addition to secret.name

**Comment by hossainemruz** [comment]
AppBinding has a `secretTransformation` field that allows specifying custom secret key and its mapping to the required keys. Unfortunately, we haven't utilized that field in Stash yet. We will support it as soon as possible.

**Comment by k0da** [comment]
So secret transformation creates clones a secret into the new one and feeds addon  with it?

Right now, I just have forked stash addon with modified constant to match zalandos secret keys. A quick workaround would be to read secrettransformation from as a key to read.

**Comment by hossainemruz** [comment]
>So secret transformation creates clones a secret into the new one and feeds addon with it?

No. Usage of this field should be in the addon side. Addon should read  the secret secret and extract the required key values  utilizing  the mapping information of secretTransformation field.

**Comment by k0da** [comment]
@hossainemruz could you pls check linked PR?

**Comment by hossainemruz** [comment]
@k0da Thank you for the PR. Currently, we are closed for Eid vacation. We will open from 31 May. I can review it then.
