### ISSUE TITLE
large names

### ISSUE THREAD

**Issue by segator** [stashed/stash#1012]
Warning  Backup Job Creation Failed  43s   BackupSession Controller  failed to create backup job for BackupSession monitoring/persistentvolumeclaim-influxdb-data-influxdb-0-bmkd8. Reason: Job.batch "stash-backup-persistentvolumeclaim-influxdb-data-influxdb-0-bmkd8" is invalid: spec.template.labels: Invalid value: "stash-backup-persistentvolumeclaim-influxdb-data-influxdb-0-bmkd8": must be no more than 63 characters.

There is a way to force simple names from BackupBlueprint for backupSession?

**Comment by hossainemruz** [comment]
Already fixed in master branch by https://github.com/stashed/stash/pull/950

**Comment by hossainemruz** [comment]
@segator This has been fixed in `v0.9.0-rc.4`. Please, try and let us know if you still face the problem.
