### ISSUE TITLE
Add doc on how to restore from BackupBatch

### ISSUE THREAD

**Issue by tamalsaha** [stashed/stash#1017]

**Comment by Amojow** [comment]
Hi, I couldn't find an documentation or example on how to restore from BackupBatch, is there any example ? Is there a way to restore everything in on configuration of RestoreSession or it is only possible with by deploying one restoreSession per component ?

**Comment by hossainemruz** [comment]
@Amojow Currently, you have to restore them separately using RestoreSession.

**Comment by hossainemruz** [comment]
Done in batch backup doc. Ref:  https://stash.run/docs/v2021.08.02/guides/latest/batch-backup/batch-backup/
