### ISSUE TITLE
Can't install stash

### ISSUE THREAD

**Issue by mxp7064** [stashed/stash#1032]
When I run curl -fsSL https://github.com/stashed/catalog/raw/master/deploy/chart.sh | bash
it returns: 
curl: (22) The requested URL returned error: 404 Not Found

When I follow instructions here: https://stash.run/docs/v0.9.0-rc.2/addons/postgres/setup/install/
I run:
curl -fsSL https://github.com/stashed/catalog/raw/v0.1.0/deploy/chart.sh | bash -s -- --catalog=stash-postgres
and it returns: Error: unknown flag: --name
That's because Helm changed their install command
Then I removed the --name flag from the chart.sh and tried again and it returns:
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Function" in version "stash.appscode.com/v1beta1", unable to recognize "": no matches for kind "Task" in version "stash.appscode.com/v1beta1"]
This also happens when I try to install it via: helm install stash-postgres-11.2 appscode/stash-postgres --version=11.2

**Comment by hossainemruz** [comment]
We have added support for Helm 3 and `chart.sh` has been removed and replaced by `helm3.sh` and `helm2.sh`. Please, try according new instruction of `v0.9.0-rc.4`.
