### ISSUE TITLE
Can't read snapshots when using BackupBatch

### ISSUE THREAD

**Issue by codejamninja** [stashed/stash#1039]
I am using BackupBatch to backup my deployments. The backups work fine.

However, when I run `kubectl get snapshots` I get the following error.

```
Error from server (InternalError): Internal error occurred: Fatal: unable to open config file: Stat: The specified key does not exist. Is there a repository at the following location? s3:s3.amazonaws.com/siliconhills-backups/stash
```

**Comment by codejamninja** [comment]
The stash operator also logs the following error.

```
/bin/restic_0.9.5 snapshots --json --quiet --no-lock --no-cache
Fatal: unable to open config file: Stat: The specified key does not exist.
Is there a repository at the following location?
s3:s3.amazonaws.com/siliconhills-backups/stash
```

**Comment by codejamninja** [comment]
But, you can see the backups exist.

![Screenshot from 2020-01-26 20-51-00](https://user-images.githubusercontent.com/6234038/73147548-97cb6380-407d-11ea-88a3-44228eff3e00.png)

**Comment by hossainemruz** [comment]
Good catch :+1: . We didn't update get snapshot for BackupBatch.

**Comment by codejamninja** [comment]
Ah, I see. Thanks. Here is what my repository looks like.

```
apiVersion: v1
items:
- apiVersion: stash.appscode.com/v1alpha1
  kind: Repository
  metadata:
    creationTimestamp: "2020-01-27T02:22:12Z"
    finalizers:
    - stash
    generation: 1
    labels:
      app: stash
      chart: stash-0.0.1
      heritage: Tiller
      io.cattle.field/appId: stash
      release: stash
    name: stash-stash
    namespace: kube-system
    resourceVersion: "45530391"
    selfLink: /apis/stash.appscode.com/v1alpha1/namespaces/kube-system/repositories/stash-stash
    uid: 92c00e01-a228-4f6a-9477-28531a9cff05
  spec:
    backend:
      s3:
        bucket: siliconhills-backups
        endpoint: s3.amazonaws.com
        prefix: stash
      storageSecretName: stash-stash-backup
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by codejamninja** [comment]
@hossainemruz so how do I restore my backups right now? Is there any workaround?

**Comment by hossainemruz** [comment]
Use `latest` in snapshot field. This will restore the latest snapshot.

**Comment by codejamninja** [comment]
What's the status on this issue?

**Comment by hossainemruz** [comment]
@codejamninja In order to fix this issue, we have to fix these issues first:
- #1053 
- #1054 

We will try to fix as soon as possible. However, it won't be part of `v0.9.0-rc.6` which going to be out very soon.

**Comment by codejamninja** [comment]
@hossainemruz ok, thanks

**Comment by nauni77** [comment]
@codejamninja Thanks for reporting. I have the same problem.

**Comment by endrec** [comment]
@hossainemruz wrote:
> Use `latest` in snapshot field. This will restore the latest snapshot.

It seems restoring from `latest` snapshot does not work with `BackupBatch`. :disappointed: 

I have a `RestoreSession` with
```
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mongo-restore
```

The restore job is created with a `--path` flag which only contains my repository prefix (it does not contain any appbinding reference).

I can create an other repository, where I add `appbinding/...` to my prefix, which works wonders, but I don't think that would be the expected way to restore from a backupbatch...

So currently my working setup is:
On backup, I have a repository, with prefix `backup`, and a BackupBatch with two targets, a mongodb and a postgres.
(This creates snapshots in `backup/appbinding/mongo` and `backup/appbinding/postgres`.)
On restore, I have two repositories, with prefixes `backup/appbinding/mongo` and `backup/appbinding/postgres`, and two RestoreSessions .
This works, but it should be simpler, I believe.

**Comment by hossainemruz** [comment]
@codejamninja We are going to fix this issue in next release. Here are the proposed changes: https://github.com/stashed/project/pull/5

**Comment by endrec** [comment]
The proposed solution looks good to me, it will make life easier. :)

**Comment by hossainemruz** [comment]
Already fixed in master.
