### ISSUE TITLE
Create RestoreBatch CRD

### ISSUE THREAD

**Issue by codejamninja** [stashed/stash#1041]
It would be nice to be able to restore batch backups. Could we create a `RestoreBatch` CRD to restore batch backups?

**Comment by hossainemruz** [comment]
Hi @codejamninja we are introducing `RestoreBatch` CRD. Here, is the respective proposal: https://github.com/stashed/project/pull/5

Checkout and give your valuable feedback.

**Comment by codejamninja** [comment]
@hossainemruz thanks

**Comment by hossainemruz** [comment]
Already done in stashed/apimachinery#22.
