### ISSUE TITLE
Stash postgres instant/one time backup

### ISSUE THREAD

**Issue by mxp7064** [stashed/stash#1058]
Hi,
I am not sure if this feature already exists, but is there a way to make an instant on-demand backup via Stash (instead of BackupConfiguration CRD/cron job) for postgres database (KubeDB), similar to Snapshot CRD?

**Comment by hossainemruz** [comment]
You can create BackupConfiguration  with `spec.paused: true`. This will not configure any schedule backup. Then, you can trigger an instant backup.
https://stash.run/docs/v0.9.0-rc.6/guides/latest/cli/cli/#trigger-an-instant-backup

**Comment by mxp7064** [comment]
Thank you!
