### ISSUE TITLE
PostgreSQL backup requires superusers

### ISSUE THREAD

**Issue by bclermont** [stashed/stash#1062]
```console
0302 15:51:15.114104       1 commands.go:120] Backing up stdin data
[golang-sh]$ pg_dumpall -U drone -h robotinfra-drone-postgresql | /bin/restic_0.9.6 backup --stdin --quiet --json -
-stdin-filename dumpfile.sql --host host-0 --cache-dir /tmp/restic-cache --cleanup-cache
pg_dumpall: query failed: ERROR:  permission denied for table pg_authid
pg_dumpall: query was: SELECT oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolconnl
imit, rolpassword, rolvaliduntil, rolreplication, rolbypassrls, pg_catalog.shobj_description(oid, 'pg_authid') as r
olcomment, rolname = current_user AS is_current_user FROM pg_authid WHERE rolname !~ '^pg_' ORDER BY 2
```

So, now I need to switch all my charts to use `postgres` user to be able to use Stash

**Comment by it-pinestack** [comment]
Same problem happens when I want to backup my Keycloak installation with attached postgres database.
 
I would welcome it if the dump script for postgres would supply an option to switch between pg_dumpall and pg_dump as backup command option.

**Comment by EivanRazgriz** [comment]
Same thing on my keycloak deployment.
Would welcome it if the backup script has an option to switch between pg_dumpall and pg_dump.

**Comment by hossainemruz** [comment]
@bclermont and @EivanRazgriz Stash now supports using custom logic using Function-Task model. You can modify our default postgres-backup function to use `pg_dump` instead of `pg_dumpall`. You have to update the following line and build a custom image.

https://github.com/stashed/postgres/blob/79247b54b00c1997ad47e16510c59d723e4b2c62/pkg/backup.go#L161

**Comment by bclermont** [comment]
I simpliy worked around this by using the [`postgresqlPostgresPassword` of helm chart](https://github.com/helm/charts/blob/ee52835ec879e82f46141810b63a09e182c43886/stable/postgresql/values.yaml#L114)

and use non-`postgres` user for the app and `postgres` for backup

**Comment by hossainemruz** [comment]
This issue should be fixed by https://github.com/stashed/postgres/pull/29. The fix should be available in next release. User can now provide the backup command during installing the addod.
