### ISSUE TITLE
BackupSession is sucessful even if backup failed

### ISSUE THREAD

**Issue by KeepMasterBranch** [stashed/stash#1064]
There is an open [issue in restic](https://github.com/restic/restic/issues/2526#issuecomment-593931863) that cause the following:

```console
{"message_type":"status","percent_done":0,"total_files":1,"total_bytes":13275}
{"message_type":"error","error":{"Op":"open","Path":"/acme/acme.json","Err":13},"during":"archival","item":"/acme/acme.json"}
{"message_type":"summary","files_new":0,"files_changed":0,"files_unmodified":0,"dirs_new":0,"dirs_changed":0,"dirs_unmodified":0,"data_blobs":0,"tree_blobs":1,"data_added":353,"total_files_processed":0,"total_bytes_processed":13275,"total_duration":0.222863199,"snapshot_id":"4f47a906"}
```

which is misleading...  as stash report a succesful backup.

I know, I need to define `securityContext`, but until that, I had false impression that data is backup. but it's not.

Should stash parse the logs for any `message_type` value `error` and mark the backup as failed?

**Comment by hossainemruz** [comment]
@bclermont Thank you for reporting.

**Comment by bclermont** [comment]
Restic just fixed the bug on their side, but they didn't have any release for the last 9 months

**Comment by bclermont** [comment]
don't care anymore

**Comment by hossainemruz** [comment]
Reopening this issue as other users might face the same problem.

**Comment by hossainemruz** [comment]
Should be fixed in the latest release.
