### ISSUE TITLE
Workload volume SS/Deployment/DS patch should check for automountServiceAccountToken

### ISSUE THREAD

**Issue by bclermont** [stashed/stash#1066]
Only one of all the workload volume backup was failing. A sidecar couldn't start:

```
W0308 09:38:49.550150       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0308 09:38:49.550181       1 client_config.go:546] error creating inClusterConfig, falling back to default config: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory
F0308 09:38:49.550319       1 run_backup.go:58] Could not get Kubernetes config: invalid configuration: no configuration has been provided
```

it was due to [`automountServiceAccountToken`](https://github.com/drone/charts/blob/dd2668e7f41f508b72274daeaf97caf840d26f1e/charts/drone/templates/deployment.yaml#L28) [reference](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server) used in Drone helm chart.

Stash operator should set that value `true` while add sidecar, and set it back to `false` if it was false to start with.

**Comment by hossainemruz** [comment]
@bclermont We don't want Stash to modify user's default configurations.

**Comment by bclermont** [comment]
@hossainemruz fair enough, but if the value if the value is false it should fail with a clear error message instead of leave users wondering why it failed

**Comment by bclermont** [comment]
don't care anymore

**Comment by mumrau** [comment]
I do care on my hand!

Please see:
- https://github.com/linkerd/linkerd2/pull/4145
- https://github.com/linkerd/linkerd2/issues/3183
- (related, less relevant) https://github.com/kubernetes/kubernetes/issues/45386

I think it would make sense to allow such change, maybe annotation based on in the CRD itself?
I would love to discuss it with you, I believe it is a very needed feature, as most open source charts and other components are moving towards better security policies, including this automount feature.
Could we reopen maybe?

**Comment by aarononeal** [comment]
I just hit this problem too since the MariaDB chart sets the value by default. Glad I found this to troubleshoot.
