### ISSUE TITLE
YAML installation guide missing essential resources

### ISSUE THREAD

**Issue by ikaruswill** [stashed/stash#1075]
## Issue & Steps

Installation using the following command recommended by [the guide](https://stash.run/docs/v0.9.0-rc.6/setup/install/) -
```
helm template stash-operator appscode/stash \
  --version v0.9.0-rc.6 \
  --namespace kube-system \
  --no-hooks | kubectl apply -f -
```
will miss out of templating of 4 resources

```
mutatingwebhookconfiguration.admissionregistration.k8s.io/admission.stash.appscode.com
clusterrole.rbac.authorization.k8s.io/appscode:stash:edit
clusterrole.rbac.authorization.k8s.io/appscode:stash:view
validatingwebhookconfiguration.admissionregistration.k8s.io/admission.stash.appscode.com
```

This causes the stash-operator deployment to not start, throwing `Error: timed out waiting for the condition` after a few minutes, and at the same time, failing healthchecks

However, the following flags, set by default by helm-template, if manually toggled to false, the deployment works immediately.
```
- --enable-mutating-webhook=true
- --enable-validating-webhook=true
```

## Solution
1. Run this command instead 
    ```
    helm template stash-operator appscode/stash \
      --version v0.9.0-rc.6 \
      --namespace kube-system \
      --output-dir ./
    ```
1. Copy the yaml printed in stdout
1. Navigate to `./stash/templates/`
1. Create a new yaml file (e.g. others.yaml)
1. Paste the copied yaml
1. Delete the `helm.sh/hook*` annotations
1. Delete the `stash-operator-cleaner` Job resource
1. (optional) Do any further annotation/metadata cleanups on templated manifests
1. Run `kubectl apply -f ./`

### Disclaimer
I'm entirely new to stash, so pardon my ignorance if any, as I've been blocked at the installation step for a long time. I'm just sharing this to save anyone many hours of debugging and to bring this to the attention of contributors/maintainers alike.

**Comment by ikaruswill** [comment]
Possibly related to #1057 as I got the same error when trying to `wget` the healthcheck endpoint from an in-container shell session.

**Comment by HubbeKing** [comment]
Also ran into this exact problem, ran around in circles trying to debug things for a few hours before I thought to look at the github issues... The solution listed above appears to work, even without any additional cleanups (step 8)

**Comment by remoe** [comment]
had the same issue. Please remove ```helm``` installation completely, not needed at all :)

**Comment by baflo** [comment]
As a side-note: this does not work with helm verison 3.3.0, as it does not give the mentioned stdout output.
A version of helm that gives it is 3.2.4.

> Solution
Run this command instead
helm template stash-operator appscode/stash \
  --version v0.9.0-rc.6 \
  --namespace kube-system \
  --output-dir ./
Copy the yaml printed in stdout
Navigate to ./stash/templates/
Create a new yaml file (e.g. others.yaml)
Paste the copied yaml
Delete the helm.sh/hook* annotations
Delete the stash-operator-cleaner Job resource
(optional) Do any further annotation/metadata cleanups on templated manifests
Run kubectl apply -f ./

**Comment by hossainemruz** [comment]
Feel free to reopen if you still facing this issue with latest Stash version.
