### ISSUE TITLE
Feature Request: Adding pg_dump alongside pg_dumpall for postgres backup

### ISSUE THREAD

**Issue by Elgarni** [stashed/stash#1086]
**Why?**
Although `pg_dumpall` works just fine, it requires `superuser` for the operation to succeed. From [postgres docs](https://www.postgresql.org/docs/12/app-pg-dumpall.html):
> Since pg_dumpall reads tables from all databases you will most likely have to connect as a database superuser in order to produce a complete dump.

This limits creating postgres backups in sitations where permissoins are fine grained, especially in cloud environments such as AWS and GCP (at least until now).

**Solution:**
Support backup using `pg_dump`. One way to implement this is using a variable `backup_tool`, where it's up to the user to select `pg_dump` or `pg_dumpall`

**Comment by Elgarni** [comment]
@hossainemruz I can PR the feature, if you don't have the time to implement it soon.

**Comment by hossainemruz** [comment]
That will be great.

**Comment by Elgarni** [comment]
Closed by [stash-postgres#29](https://github.com/stashed/postgres/pull/29)
