### ISSUE TITLE
Restoring application with node coordination

### ISSUE THREAD

**Issue by Amojow** [stashed/stash#1096]
Restoring a clustered application, which depends on all of its nodes to be ready to be launched, is failing. 

**Environment :** 
Stash v0.9.0-rc.6
Kubernetes 1.16

**Steps to reproduce :** 
Backup then restore an application that needs all of its nodes to be started
In my case, i tried to restore a multi node rabbitmq. I deployed it as a Statefulset and tried to restore it. 

**What's my issue and how to solve it ?** 
I find that while the first node to be restored is not in a ready state (readiness probe), the restore process doesn't go forward to restore the others statefulset's nodes. 
Then i found out that if i manually remove the readiness and liveness probe of the statefulset, the restore process is complete and my rabbitmq application is fully restored (and working). 

**Enhancement proposed :** 
**Feature to pause healthchecks** (liveness and readiness probe) of a ressource which is being restored.

**Comment by hossainemruz** [comment]
>Feature to pause healthchecks (liveness and readiness probe) of a ressource which is being restored.

Stash should not modify user resources apart from injecting sidecar/init-container.

Databases should use database specific backup and restore methods. Stash has addons for various databases. Unfortunately, rabitmq is not there.

However, in your case, you can first restore the PVCs then deploy your StatefulSet using that PVCs similar to the example here. https://stash.run/docs/v0.9.0-rc.6/addons/percona-xtradb/guides/5.7/clustered/#create-restoresession

**Comment by Amojow** [comment]
Thank you for the response, i'll search an other way to make the rabbitmq cluster reload without modifying Kubernetes ressources.
