### ISSUE TITLE
[Question] How do I define exclude patterns in BackupConfiguration 

### ISSUE THREAD

**Issue by asoltesz** [stashed/stash#1098]
I have folders on my volume that contain files and subfolders that I would like to exclude from the backup (temporary upload files...etc).  

How do I define these excludes?

I didn't find info on this in the filesystem/restic guide.

**Comment by hossainemruz** [comment]
Already done in master. Ref: https://stash.run/docs/v2020.11.17/concepts/crds/backupconfiguration/#spectarget
