### ISSUE TITLE
Using Prometheus to confirm that a backup ran within <period>

### ISSUE THREAD

**Issue by funkypenguin** [stashed/stash#1100]
Hey folks!

have a question re prometheus.. I've worked out that I can create an alert to alarm if `stash_backup_session_success` is not 1, which will alert me to a failed backup. Great. But I'm wondering how to provide assurance that a backup has run within x hours? I.e., my current solution wouldn't alert me if a backup got "stuck" or silently failed for some other reason...

Thanks!
David

**Comment by hossainemruz** [comment]
Maybe we can introduce a metrics called `stash_last_backup_success_time_seconds` where time will be in unix epoc.

**Comment by funkypenguin** [comment]
Following on from our Slack conversation, perhaps a metric indicating the unix timestamp of the last backup (whether successful or not)?

**Comment by hossainemruz** [comment]
Already added in the latest releases.
