### ISSUE TITLE
stash 0.8.3 - how to remove the sidecar once stash has been uninstalled?

### ISSUE THREAD

**Issue by michael-niemand** [stashed/stash#1109]
I uninstalled stash before removing the restics, thinking the sidecars would be removed, too.
I read the documentation for an older version, where it states that you need to remove the restics so the stash operator will remove the sidecars.
So I re-installed stash, installed and removed the restics bit the sidecars are still there. How do I get rid of them?

**Comment by hossainemruz** [comment]
Any log from Stash operator?

**Comment by michael-niemand** [comment]
I already uninstalled stash again since it didn't help with removing the sidecars. The logs didn't say anything in regards to the restics, but I was able to patch the deployment to remove the container. So in case someone runs into the same issue and Google sends them here:
`kubectl patch deployment \<name-of-your deployment\> --type json   -p='[{"op": "remove", "path": "/spec/template/spec/containers/\<number of the stash pod starting from 0\>"}]'`
