### ISSUE TITLE
The server is currently unable to handle the request

### ISSUE THREAD

**Issue by cwrau** [stashed/stash#1128]
We're using `flux` to sync our git configuration into the cluster. For a few days now, flux fails with the following error:

```
couldn't get resource list for admission.stash.appscode.com/v1beta1: the server is currently unable to handle the request
```

When I deleted that API service, the error changed to:

```
couldn't get resource list for admission.stash.appscode.com/v1alpha1: the server is currently unable to handle the request
couldn't get resource list for repositories.stash.appscode.com/v1alpha1: the server is currently unable to handle the request
couldn't get resource list for admission.stash.appscode.com/v1alpha1: the server is currently unable to handle the request
```

After I deleted them, it changed to:

```
couldn't get resource list for admission.stash.appscode.com/v1alpha1: the server could not find the requested resource
```

Also the `stash` pod itself constantly writes the following error:

```
remote error: tls: bad certificate
```

Stash is deployed in version `v0.9.0-rc.6` in the `backup` namespace via helm3

**Comment by cwrau** [comment]
Ah!

While typing our setup, stash in `backup` namespace, I was thinking about trying to deploy stash in the `kube-system` namespace.

Sure enough, that seems to have worked!



It should be documented, that stash only works inside the `kube-system` namespace, or better yet, make stash work in any workspace!

**Comment by cwrau** [comment]
Now it happens again:

```
collating resources in cluster for sync: the server is currently unable to handle the request
```

**Comment by athak** [comment]
This is happening to us too. We initially installed `stash` in a different namespace than `kube-system` and were seeing the same errors trying to add a `Repository`. Uninstalling and re-installing in `kube-system` has not solved the issue.

Any ideas what's going on, workarounds? We are blocked in our evaluation due to this.

**Comment by hossainemruz** [comment]
Try with latest Stash version. Feel free to reopen if you still face the issue.
