### ISSUE TITLE
Apply user defined annotations on job pods

### ISSUE THREAD

**Issue by MarkLehmacherInvestify** [stashed/stash#1133]
I am using stash within a namespace where linkerd proxy injection is active on namespace level.

This means that all pods being spawned from jobs having been induced by the cronjob having been created by the stash operator from my BackupConfiguration receive a linkerd proxy sidecar. I would like to disable this behavior by applying an annotation to the job pod.

With 0.9.0-rc6 this leads to the following problem when a job is spawned and in turn tries to create a BackupSession: `create_backupsession.go:79] <nil>`

Unfortunately the exact error is not being logged due to a [bug](https://github.com/stashed/stash/blob/473dab81bfc0d3f8085b2fbf99c03143501d991d/pkg/cmds/create_backupsession.go#L78) where err is not reassigned (this already been fixed on master).

**Comment by MarkLehmacherInvestify** [comment]
Actually my issue is a duplicate of https://github.com/stashed/stash/issues/1070

**Comment by hossainemruz** [comment]
Closing in favor of #1070
