### ISSUE TITLE
stash-operator is not getting installed in kubernetes cluster without internet access

### ISSUE THREAD

**Issue by ragunathan23** [stashed/stash#1134]
Hi,
Trying to install a stash-operator in the Kubernetes cluster which has no internet access. The images( appscode/stash:0.6.0 ,prom/pushgateway:v0.4.0) are locally available in the docker.  The appscode/stash container gets into a crash loop with the following error:

ERROR LOG:
registry.ping url=https://registry-1.docker.io/v2/
run.go:43] Image appscode/stash:0.6.0 not found.
│ <STREAM> closed 

Do we need internet access for the stash to work even though we have images locally? Can we ignore the registry ping URL call?

**Comment by hossainemruz** [comment]
By default, Stash uses `imagePullPolicy: IfNotPresent.` So, it should not try to pull the image it is already present.
https://github.com/stashed/stash/blob/dfc1e90bd996d08a230eced62d5fbae29a9a22c6/chart/stable/stash/values.yaml#L20

Btw, you are using a very old version of Stash. We recommend to update to the newer version. We no longer provide any bug-fixes for old version.

**Comment by ragunathan23** [comment]
@hossainemruz Thanks for the reply.

I tried installing via YAML and the following file is specified in the Stash setup instruction. 

https://raw.githubusercontent.com/appscode/stash/0.6.0/hack/deploy/with-rbac.yaml

As I mentioned, there is no problem with the image loading as they are available in the local docker. The registry url ping is was causing the problem. 

Can you also point me to the newer version of yaml file for stash-operator?

**Comment by hossainemruz** [comment]
Here are the installer file for newer version: https://github.com/stashed/installer

Beware that there has been lots of changes between `0.6.0` and `0.9.x`. Make sure you have understand the new model first.
https://stash.run/docs/v0.9.0-rc.6/concepts/

**Comment by ragunathan23** [comment]
I followed the following steps:
$ helm repo add appscode https://charts.appscode.com/stable/
$ helm repo update
$ helm search repo appscode/stash --version v0.9.0-rc.6

But getting No results found.

Moreover i could not see the appscode/stash repo and this repo appscode/git-apiserver is listed

**Comment by ragunathan23** [comment]
Sorry for the inconvenience, had some proxy issue, able to convert chart to yaml

**Comment by ragunathan23** [comment]
@hossainemruz able to run with the latest version, closing this issue.
