### ISSUE TITLE
Feature Request: Allow setting concurrencyPolicy

### ISSUE THREAD

**Issue by aarononeal** [stashed/stash#1137]
`BackupConfiguration` and `BackupBlueprint` allow setting `schedule` for the generated `CronJob` but do not allow setting `concurrencyPolicy`.

The default is `Always` but if a job is long running I want to `Forbid` it from starting a new instance.

**Comment by aarononeal** [comment]
I manually set the `CronJob` to `concurrencyPolicy: Forbid` but it started a second backup job anyway interfering with the first.

I think it may have to do with the PVC pod performing backup during `PodInitialize` and so cron thinks the job isn't running yet.

Is there a reason stash needs to run the PVC backup as an init container instead of a regular one? This also triggers warnings in my monitoring tool because these pods have hour long `Pending` status starting.

I have TB of data to backup and it's not realistic for the first-time backup to complete within the normal ongoing schedule window.

**Comment by aarononeal** [comment]
Just realized one of the reasons setting `concurrencyPolicy: Forbid` has no effect is because the job that runs just queues a request to the stash sidecar and exits. So when time comes back around, there is no job that K8S is aware of and it kicks off another backup session request. 

This results in either a failure due to locks, a dangerous overlapping job (if there is an unlock pre-hook), or a queue of pending jobs depending on how I have things configured.

I'm not sure how to get the desired behavior of running only one instance of a job at a time while avoiding session queueing. I don't need it to run 9 backups in a row when a long running initial backup finally finishes.

**Comment by hossainemruz** [comment]
Stash now automatically skip backup if there is already a running backup.  So, this problem should be fixed. Feel free to reopen if it doesn't.
