### ISSUE TITLE
documentation is missing pointers on how to debug errors

### ISSUE THREAD

**Issue by FlorianLudwig** [stashed/stash#1152]
For example https://stash.run/docs/v0.9.0-rc.6/addons/postgres/guides/11.2/standalone/ states "Wait for BackupSession" and "We can see above that the backup session has succeeded" but does not mention any help what to do when the status is not "Succeeded".

**Comment by FlorianLudwig** [comment]
The documentation seems not to include the word "[debug](https://github.com/stashed/docs/search?q=debug&unscoped_q=debug)".

The word "[log](  https://github.com/stashed/docs/search?l=Markdown&p=2&q=log)"  is 57 times in the docs but non of the results help me find (helpful) logs about my backups.

**Comment by hossainemruz** [comment]
Hi @FlorianLudwig thank you for your feedback. Stash is continuously evolving. We are currently more focused on features. So, this kind of debugging doc will get outdated soon. That's why we didn't spend time on it. Once we are satisfied with feature sets, we will focus on user experience.

**Comment by FlorianLudwig** [comment]
As I just learned stash is getting relicensed as an enterprise product. So the open source docs are no longer of interest I guess, so I close this issue.
