### ISSUE TITLE
Add an option to disable --force on the restic command

### ISSUE THREAD

**Issue by thlassche** [stashed/stash#1153]
When looking at a backup process the cmd looks like this:

`/bin/restic backup <dir> --force --hostname <hostname> --cache-dir /tmp/restic-cache`

The `--force` flag is quite expensive, it forces a re-read of all target directories: https://restic.readthedocs.io/en/latest/manual_rest.html

Is there a particular reason the `--force` flag is added? And can we make it optional?

**Comment by hossainemruz** [comment]
Which version of Stash are you using? Stash doesn't use this `--force` flag.
Ref: https://github.com/stashed/apimachinery/blob/0f69a3abd373d898122d9a7801f68242d8b9ece5/pkg/restic/commands.go#L99

**Comment by thlassche** [comment]
@hossainemruz We are using 0.8.3
Are you sure restic is not using that flag? See: https://github.com/stashed/stash/blob/master/pkg/cli/restic.go#L103

**Comment by hossainemruz** [comment]
That old version used this flag.
Ref: https://github.com/stashed/stash/blob/ccf4469b2934ed26f47d157425e75926e6043ac3/pkg/cli/restic.go#L86

New version has removed it. Try new version.

**Comment by thlassche** [comment]
@hossainemruz Are you sure? I linked the master branch file, which still has it and the 0.10 release branch also has it:

https://github.com/stashed/stash/blob/release-0.10/pkg/cli/restic.go#L103

**Comment by hossainemruz** [comment]
These file are there for old APIs. For backward compatibility. New v1beta1 apis uses the package i linked in my first comment. Now, restic related things lives in `restic` package of `stashed/apimachinary` repo.
