### ISSUE TITLE
update-status has error "unexpected status code 200"

### ISSUE THREAD

**Issue by caohhung** [stashed/stash#1161]
Hi team,
I got a weird issue which pushgateway return 200 successful HTTP code but sidecar/job still complain about unexpected status code

`unexpected status code 200 while pushing to http://stash.kube-system.svc:56789/metrics/...`

In [push.go](https://github.com/stashed/stash/blob/master/vendor/github.com/prometheus/client_golang/prometheus/push/push.go#L253), it only allows 202 status code. But according to [prometheus/pushgateway](https://github.com/prometheus/pushgateway/blob/master/README.md#put-method) document, pushgateway return both 200 and 202 status code.

Any idea how to fix it?

**Comment by caohhung** [comment]
Hello @hossainemruz , may I ask you if this is real bug or something relates to configuration?
Do you have any workaround/solution to fix it?

**Comment by hossainemruz** [comment]
It seems they have fixed it in master. We have to update the library version.
https://github.com/prometheus/client_golang/blob/4675060215e9866ac3e834cfd62ba3fb36b89e12/prometheus/push/push.go#L277

**Comment by hossainemruz** [comment]
When we vendor stashed/apimachinery#44 to stashed/stash project, this issue should be fixed.
