### ISSUE TITLE
Custom pushgateway

### ISSUE THREAD

**Issue by caohhung** [stashed/stash#1162]
Hello team,
We're using stash to backup both PV and PG database.
We already have pushgateway to collect metrics from other service. Are there any solution to push metrics from stash to this pushgateway instead of the build-in in stash?

**Comment by hossainemruz** [comment]
No. Currently, it's not configurable.

**Comment by caohhung** [comment]
@hossainemruz Thanks for your confirmation.
So far do you have any plan to make it configurable? If not, the only solution is custom docker image, right?

**Comment by hossainemruz** [comment]
Currently, we don't have any plan to support it. Yes, you have to make custom Docker image. 

Btw, keep this issue open. We may support this in future.

**Comment by caohhung** [comment]
Thank you, glad to hear that.

**Comment by Rojikku** [comment]
I still want this two years later and I'm fairly confident getting a URL from an env variable isn't that hard.
However you'd want to implement it would be fine with me.
Then with the chart just have an enable true/false, which you can do based on the helm example when you create a new helm chart.

**Comment by hossainemruz** [comment]
Yes. This isn't hard to implement. It just hasn't been a priority for us.

Btw, we are removing pushgateway entirely in next api version upgrade (probably going to be re-branded with a different name). We will be using a different mechanism for generating Prometheus metrics. That will give the users ability to customize their own metrics.

**Comment by hossainemruz** [comment]
I think we can add this in the next release. It will require us to add a new flag. Adding to current sprint.
