### ISSUE TITLE
stash-init container executed after other init-container

### ISSUE THREAD

**Issue by caohhung** [stashed/stash#1164]
Hello team,
We're using stash to backup Deployment's PV.
In Deployment, we also define a `custom-init` container to check/validate something before main container is up.

Combine with `stash-init`, our `custom-init` always run before `stash-init` during the restore, which break our procedure

Expected flow: `stash-init` -> `custom-init` -> `main container`
Actual flow:  `custom-init` -> `stash-init` -> `main container`

Do we have any solution to make sure that stash-init is inject in the top or the bottom of init flow?

**Comment by hossainemruz** [comment]
@caohhung Thank you for reporting this bug. We should change the order here:
https://github.com/stashed/stash/blob/378de04d860fe4df55f8d3428b2c5be7683eb4ea/pkg/controller/init_container.go#L87

We will fix as soon as possible.

**Comment by caohhung** [comment]
Thanks for your quick response, @hossainemruz

**Comment by caohhung** [comment]
Hello @hossainemruz , is this possible solution to fix it https://github.com/stashed/stash/pull/1165 ?
