### ISSUE TITLE
Sessions stuck in Running

### ISSUE THREAD

**Issue by drallgood** [stashed/stash#1170]
I have multiple backup configurations based on the latest docu (Deployment/Statefulset).
ALL of them are stuck in "Running" state with zero information anywhere what's going on.
The sidecars seem to be fine (no errors or any indication they're doing anything)
No jobs in the queue.. just.. nothing.
![Screen Shot 2020-08-09 at 3 45 43 PM](https://user-images.githubusercontent.com/127142/89733673-646b8780-da57-11ea-918d-ca7afdccc31a.png)

Any ideas?

I'm using rc.6

**Comment by dhrp** [comment]
If they're running, there should be a pod running too.. Check the logs of such pod.

**Comment by hossainemruz** [comment]
Feel free to reopen if you still face the issue after upgrading to the latest version.
