### ISSUE TITLE
Panic at startup

### ISSUE THREAD

**Issue by bclermont** [stashed/stash#1190]
I'm trying to migrate to Stash 0.10.0 and the operator panic:

```
E0912 14:46:02.564769       1 controller.go:183] timed out waiting for caches to sync
panic: timed out waiting for the condition
goroutine 744 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
        /src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:171
kmodules.xyz/client-go/admissionregistration/v1beta1.SyncValidatingWebhookCABundle.func3(0x2c04100, 0xc000883e80, 0xc001524060, 0xc000533080, 0xc0008
c7200)
        /src/vendor/kmodules.xyz/client-go/admissionregistration/v1beta1/validatingwebhookconfiguration.go:218 +0x135
created by kmodules.xyz/client-go/admissionregistration/v1beta1.SyncValidatingWebhookCABundle
        /src/vendor/kmodules.xyz/client-go/admissionregistration/v1beta1/validatingwebhookconfiguration.go:190 +0x1dc
```

**Comment by bclermont** [comment]
Nevermind, I just noticed that Batch Backup & Batch Restore are not part of the open source version, I'm giving up on stash

**Comment by hossainemruz** [comment]
@bclermont we are sorry to hear that you are giving up on Stash. We understand the reason. We hope you will understand our reason too.

We will like you to continue using Stash. As a contributor, you deserve special care. Please, setup a short meeting [here](https://calendly.com/appscode/30min?month=2020-09). We will like to discuss how we can make it work for you.

**Comment by bclermont** [comment]
It's ok thanks, I just finished migration to velero
