### ISSUE TITLE
How to solve if aws-ebs does not support ReadWriteMany

### ISSUE THREAD

**Issue by huzerun0306** [stashed/stash#1271]
The provisioner of our StorageClass is aws/ebs, but it cannot support ReadWriteMany, how can I use stash to backup the pvc of aws/ebs

**Comment by hossainemruz** [comment]
You can use [workload backup](https://stash.run/docs/v2020.11.17/guides/latest/workloads/overview/).

**Comment by huzerun0306** [comment]
Hello, please ask a question. I created a bucket called stashtest and created a /data directory in this bucket. We can see that the s3 url is s3://stashtest/data/, and then I create a Repository
`s3:
      endpoint: s3.amazonaws.com
      bucket: stashtest
      region: us-west-2
      prefix: /data
`
I saw the following error in the sidecar container log, and the INTEGRITY field of my Repository is empty and not true . Is there any problem with my configuration

`
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
Fatal: unable to open config file: Stat: The specified key does not exist.
Is there a repository at the following location?
s3:s3.amazonaws.com/stashtest/data
I1119 07:43:55.320782       1 commands.go:109] Initializing new restic repository in the backend....
[golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache
I1119 07:43:57.969701       1 commands.go:398] sh-output: created restic repository 75991d0db9 at s3:s3.amazonaws.com/stashtest/data

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

I1119 07:43:57.987807       1 commands.go:118] Backing up target data
[golang-sh]$ /bin/restic backup /data --quiet --json --host host-0 --cache-dir /tmp/restic-cache --cleanup-cache
/data does not exist, skipping
Fatal: all target directories/files do not exist
W1119 07:43:57.996367       1 backupsession.go:487] Failed to take backup for BackupSession deployment-backup-1605770709. Reason: /data does not exist, skipping Fatal: all target directories/files do not exist
I1119 07:43:57.996387       1 status.go:115] Updating post backup status.......
I1119 07:43:58.017369       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605771610
I1119 07:43:58.020357       1 backupsession.go:226] Skip processing BackupSession stash/deployment-backup-1605771610. Reason: Backup process is not initiated by the operator
I1119 07:43:58.020421       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605770709
I1119 07:43:58.023299       1 backupsession.go:221] Skip processing BackupSession stash/deployment-backup-1605770709. Reason: BackupSession has been processed already for host "host-0"
I1119 07:43:58.027275       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605770709
I1119 07:43:58.030693       1 backupsession.go:221] Skip processing BackupSession stash/deployment-backup-1605770709. Reason: BackupSession has been processed already for host "host-0"
I1119 07:45:11.184036       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605771911
I1119 07:45:11.187326       1 backupsession.go:226] Skip processing BackupSession stash/deployment-backup-1605771911. Reason: Backup process is not initiated by the operator
I1119 07:45:11.200301       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605771911
I1119 07:45:11.212509       1 commands.go:98] Checking whether the backend repository exist or not....
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
I1119 07:45:12.357534       1 commands.go:398] sh-output: []

I1119 07:45:12.378069       1 commands.go:118] Backing up target data
[golang-sh]$ /bin/restic backup /data --quiet --json --host host-0 --cache-dir /tmp/restic-cache --cleanup-cache
/data does not exist, skipping
Fatal: all target directories/files do not exist
W1119 07:45:12.387657       1 backupsession.go:487] Failed to take backup for BackupSession deployment-backup-1605771911. Reason: /data does not exist, skipping Fatal: all target directories/files do not exist
I1119 07:45:12.387675       1 status.go:115] Updating post backup status.......
`

**Comment by huzerun0306** [comment]
@hossainemruz  Hello, please ask a question. I created a bucket called stashtest and created a /data directory in this bucket. We can see that the s3 url is s3://stashtest/data/, and then I create a Repository
```
s3:
      endpoint: s3.amazonaws.com
      bucket: stashtest
      region: us-west-2
      prefix: /data
```
I saw the following error in the sidecar container log, and the INTEGRITY field of my Repository is empty and not true . Is there any problem with my configuration

```
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
Fatal: unable to open config file: Stat: The specified key does not exist.
Is there a repository at the following location?
s3:s3.amazonaws.com/stashtest/data
I1119 07:43:55.320782       1 commands.go:109] Initializing new restic repository in the backend....
[golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache
I1119 07:43:57.969701       1 commands.go:398] sh-output: created restic repository 75991d0db9 at s3:s3.amazonaws.com/stashtest/data

Please note that knowledge of your password is required to access
the repository. Losing your password means that your data is
irrecoverably lost.

I1119 07:43:57.987807       1 commands.go:118] Backing up target data
[golang-sh]$ /bin/restic backup /data --quiet --json --host host-0 --cache-dir /tmp/restic-cache --cleanup-cache
/data does not exist, skipping
Fatal: all target directories/files do not exist
W1119 07:43:57.996367       1 backupsession.go:487] Failed to take backup for BackupSession deployment-backup-1605770709. Reason: /data does not exist, skipping Fatal: all target directories/files do not exist
I1119 07:43:57.996387       1 status.go:115] Updating post backup status.......
I1119 07:43:58.017369       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605771610
I1119 07:43:58.020357       1 backupsession.go:226] Skip processing BackupSession stash/deployment-backup-1605771610. Reason: Backup process is not initiated by the operator
I1119 07:43:58.020421       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605770709
I1119 07:43:58.023299       1 backupsession.go:221] Skip processing BackupSession stash/deployment-backup-1605770709. Reason: BackupSession has been processed already for host "host-0"
I1119 07:43:58.027275       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605770709
I1119 07:43:58.030693       1 backupsession.go:221] Skip processing BackupSession stash/deployment-backup-1605770709. Reason: BackupSession has been processed already for host "host-0"
I1119 07:45:11.184036       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605771911
I1119 07:45:11.187326       1 backupsession.go:226] Skip processing BackupSession stash/deployment-backup-1605771911. Reason: Backup process is not initiated by the operator
I1119 07:45:11.200301       1 backupsession.go:185] Sync/Add/Update for Backup Session deployment-backup-1605771911
I1119 07:45:11.212509       1 commands.go:98] Checking whether the backend repository exist or not....
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
I1119 07:45:12.357534       1 commands.go:398] sh-output: []

I1119 07:45:12.378069       1 commands.go:118] Backing up target data
[golang-sh]$ /bin/restic backup /data --quiet --json --host host-0 --cache-dir /tmp/restic-cache --cleanup-cache
/data does not exist, skipping
Fatal: all target directories/files do not exist
W1119 07:45:12.387657       1 backupsession.go:487] Failed to take backup for BackupSession deployment-backup-1605771911. Reason: /data does not exist, skipping Fatal: all target directories/files do not exist
I1119 07:45:12.387675       1 status.go:115] Updating post backup status.......
```

**Comment by hossainemruz** [comment]
Can you please show the YAML of the BackupConfiguration and the respective workload?

**Comment by huzerun0306** [comment]
@hossainemruz 
deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: stash-demo
  name: stash-demo
  namespace: stash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stash-demo
  template:
    metadata:
      labels:
        app: stash-demo
      name: busybox
    spec:
      containers:
      - args: ["echo sample_data > /source/data/data.txt && sleep 3000"]
        command: ["/bin/sh", "-c"]
        image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        volumeMounts:
        - mountPath: /source/data
          name: source-data
      restartPolicy: Always
      volumes:
      - name: source-data
        persistentVolumeClaim:
          claimName: stash-sample-data
```

BackupConfiguration.yaml
```
apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: deployment-backup
  namespace: stash
spec:
  repository:
    name: s3-repo
  schedule: "*/5 * * * *"
  target:
    ref:
      apiVersion: apps/v1
      kind: Deployment
      name: stash-demo
    volumeMounts:
    - name: source-data
      mountPath: /source/data
    paths:
    - /data         
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
```

repo.yaml
```
apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: s3-repo
  namespace: stash
spec:
  backend:
    s3:
      endpoint: s3.amazonaws.com # use server URL for s3 compatible other storage service
      bucket: stashtest
      region: us-west-2
      prefix: /data
    storageSecretName: s3-secret
```

**Comment by hossainemruz** [comment]
This
```yaml
   paths:
    - /data   
```
Should be
```yaml
   paths:
    - /source/data   
```
Your volume has been mounted into `/source/data` directory. So, the `/source/data` directory exit in the container but not the `/data` directory.

**Comment by huzerun0306** [comment]
@hossainemruz  Thank you very much, but I don’t understand why there are two paths here despite the explanation in the documentation.
```
target.volumeMounts.mountPath
target.paths
```
What is the difference between them? You answered me earlier: ```Your volume has been mounted into /source/data directory```，So the target.volumeMounts.mountPath I filled in is /source/data, so why do I need to fill in a target.paths and what is its function?

**Comment by hossainemruz** [comment]
- `target.volumeMounts.mountPath`:  This specifies where the source volume will be mounted. For example, here `/source/data`.

- `target.paths`: This specifies which path you want to take backup. If you want take backup of the full volume, you can just specify the same path that you have used in mountPath(i.e. `/source/data`). You can take backup of any sub path of the volume or even any single file. For example, `/source/data/my/data`, `/source/data/my/data/demo.txt` etc.
