### ISSUE TITLE
Stash not working on docker-desktop kubernetes

### ISSUE THREAD

**Issue by hgibsonqb** [stashed/stash#1302]
Hi,

I installed the community edition of stash following [these instructions (https://stash.run/docs/v2021.01.21/setup/install/community/) and am trying to backup a deployment. I've created a minio deployment, stash s3-secret and repository, and a backup configuration.

However, nothing is happening. Stash is supposed to create a cronjob and backup session which isn't happening. Also, I don't see anything in the stash operator pod logs.

Any idea why this isn't working and advice on how to troubleshoot?

I can post yaml files for minio deployment, target deployment, stash operator/base resources, stash backupconfiguration, repo, etc if that would be useful.

**Comment by hgibsonqb** [comment]
Here is my setup https://gist.github.com/hgibsonqb/bc5002221345e5ef8e832329eb9a086b

**Comment by tamalsaha** [comment]
Thanks! Could you please share the logs from the `stash` operator pod in kube-system namespace?

**Comment by hgibsonqb** [comment]
Sure https://gist.github.com/hgibsonqb/ea0d55832847145d08ae6b5061ec8f2c

**Comment by tamalsaha** [comment]
Hey,
I think we have found the problem in the helm chart and addressed it here: https://github.com/stashed/installer/pull/138. The core issue was that we were using --no-hooks command, which resulted in some necessary YAMLs not getting generated.

To use the updated chart, please follow the instructions below: 

1. Update existing helm cache.

```
rm -rf $HOME/Library/Caches/helm
helm repo update
```

2. Run the following command again to install the stash operator:

```
$ helm template stash appscode/stash          \
  --version v0.11.9                \
  --namespace kube-system                     \
  --set-file license=/path/to/the/license.txt \
  --set cleaner.skip=true | kubectl apply -f -
```

3. This time, you should not see the apiservice error you saw last time. You might see it at first, but it should go away within 30-60 secs.

```
watch kubectl get apiservice
```

4. After that Stash operator should be ok to use.

Please let us know how it goes. Thanks!

**Comment by hgibsonqb** [comment]
Hi,

That fixed it thanks!

**Comment by tamalsaha** [comment]
Glad to hear that! Let us know if there are any other questions.
