### ISSUE TITLE
Unable to Recover PVC 

### ISSUE THREAD

**Issue by harshit895** [stashed/stash#1360]
**Getting the below error in the recovery :**
```
Events:
  Type     Reason              Age   From            Message
  ----     ------              ----  ----            -------
  Normal   RecoveryJobCreated  22s   stash-operator  Recovery job created: stash-recovery-pvc-recovery
  Warning  FailedRecovery      10s   stash-recovery  failed to recover FileGroup /var/lib/mysql, reason:   /usr/local/go/src/runtime/asm_amd64.s:2361
  Warning  FailedRecovery      10s   stash-recovery  Failed to complete recovery pvc-recovery, reason: %!s(<nil>)
```

**Logs from the recovery container which lasts for a few seconds only :** 
```
ignoring error for /mysql/#ib_16384_0.dblwr: OpenFile: open /var/lib/mysql/#ib_16384_0.dblwr: permission denied
ignoring error for /mysql: UtimesNano: no such file or directory
ignoring error for /mysql: Chmod: chmod /var/lib/mysql: operation not permitted
There were 3 errors
operation not permitted
UtimesNano
github.com/restic/restic/internal/restic.Node.RestoreTimestamps
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/restic/node.go:235
github.com/restic/restic/internal/restic.(*Restorer).restoreTo
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/restic/restorer.go:104
github.com/restic/restic/internal/restic.(*Restorer).RestoreTo
        /tmp/restic-build-413028034/src/github.com/restic/restic/internal/restic/restorer.go:156
main.runRestore
        src/github.com/restic/restic/cmd/restic/cmd_restore.go:155
main.glob..func19
        src/github.com/restic/restic/cmd/restic/cmd_restore.go:24
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/restic-build-413028034/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:698
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/restic-build-413028034/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:783
github.com/restic/restic/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/restic-build-413028034/src/github.com/restic/restic/vendor/github.com/spf13/cobra/command.go:736
main.main
        src/github.com/restic/restic/cmd/restic/main.go:69
runtime.main
        /usr/local/go/src/runtime/proc.go:198
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:2361
```

**Please help me resolve this issue. Thanks !**

**Comment by hossainemruz** [comment]
What is your Stash version? Can you please share the YAML you are using to restore?

**Comment by harshit895** [comment]
Stash version is : v0.9.0-rc.6. I installed stash using helm3 from this link : https://stash.run/docs/v0.9.0-rc.6/setup/install/

Below is the yaml for Restore I'm using : 

apiVersion: stash.appscode.com/v1alpha1
kind: Recovery
metadata:
  name: pvc-recovery
  namespace: default
spec:
  repository:
    name: deployment.mysql-test
    namespace: default
  snapshot: deployment.mysql-test-041e179d # skip this field to recover latest snapshot
  paths:
  - /var/lib/mysql
  recoveredVolumes:
  - mountPath: /var/lib/mysql
    hostPath:
      path: /var/lib/mysql

**Comment by hossainemruz** [comment]
You are using a very old build. Lots of things has changed since then. Please try with latest version.
https://stash.run/docs/v2021.06.23/setup/install/community/

**Comment by harshit895** [comment]
After doing a fresh install of this version of stash. Now the recovery doesn't complete though i had put only 2 files in the volume (approx 10kb each) for testing: 

![image](https://user-images.githubusercontent.com/58470860/125145657-bd4c1000-e13f-11eb-9408-fde43033d13d.png)

**Comment by hossainemruz** [comment]
Hey @harshit895! Were you able to solve the issue?

**Comment by harshit895** [comment]
No. I have dumped stash and gove with a different solution. You can close this issue now
