### ISSUE TITLE
[stashed/apimachinery] Optimize memory consumption of restic wrapper

### ISSUE THREAD

**Issue by weisdd** [stashed/stash#1376]
`stashed/apimachinery` keeps stdout of restic in memory:

```go
func (w *ResticWrapper) run(commands ...Command) ([]byte, error) {
	// write std errors into os.Stderr and buffer
	errBuff, err := circbuf.NewBuffer(256)
	if err != nil {
		return nil, err
	}
	w.sh.Stderr = io.MultiWriter(os.Stderr, errBuff)

	for _, cmd := range commands {
		if cmd.Name == ResticCMD {
			// first apply NiceSettings, then apply IONiceSettings
			cmd, err = w.applyNiceSettings(cmd)
			if err != nil {
				return nil, err
			}
			cmd, err = w.applyIONiceSettings(cmd)
			if err != nil {
				return nil, err
			}
		}
		w.sh.Command(cmd.Name, cmd.Args...)
	}
	out, err := w.sh.Output()
	if err != nil {
		return nil, formatError(err, errBuff.String())
	}
	klog.Infoln("sh-output:", string(out))
	return out, nil
}
```
[Source code](https://github.com/stashed/apimachinery/blob/cdbb8e52c1adefbfe7800ac6d0d1fa279d69bfe7/pkg/restic/commands.go#L398)

When backing up hundreds of thousands of files, it leads to big memory consumption during backup phase, because, by default, restic reports its progress too frequently, basically a line (=> json) per file.
Solution to that is very simple. Current version of restic supports the `RESTIC_PROGRESS_FPS` env, which tunes the frequency of reporting. If you set it to `0.01666`, it's going to be only one message a minute.

Without `RESTIC_PROGRESS_FPS="0.01666"` being set:
![stash-memory-combined](https://user-images.githubusercontent.com/46579601/130412985-d8a707b4-4628-4964-b8b8-3389fb629c91.png)

With `RESTIC_PROGRESS_FPS="0.01666"`:
![stash-memory-combined-fixed](https://user-images.githubusercontent.com/46579601/130413034-94e45a2a-f639-4bf3-b83f-612958f8f034.png)

So, here, the memory consumption during backup phase went down by ~3 GiB. 

In the custom plugin that I used in this example, the fix looked like this:

```go
	resticProgressFPSEnv := "RESTIC_PROGRESS_FPS"
	_, ok := os.LookupEnv(resticProgressFPSEnv)
	if !ok {
		// Set it to one message per minute
		os.Setenv(resticProgressFPSEnv, "0.01666")
	}
```

I think it'd make a lot of sense to do the same in `stashed/apimachinery' itself rather than adding it to every `BackupConfiguration` or plugin.

///

As a side question, what are the reasons not to use `Multiwriter` for `io.stdout`? (currently, it's used only for stderr) That could help to me more informative during backup phase, so the progress gets reported throughout the whole process, not only at the end.

**Comment by hossainemruz** [comment]
Thank you @weisdd for pointing out this. We have also noticed this issue and  solved this in the latest `v2021.08.02` release of Stash by modifying the underlying restic code where we have limited the number of reports get printed. Now, it will print at most 100 reports during a backup. We didn't know about the existence of `RESTIC_PROGRESS_FPS` env.


>As a side question, what are the reasons not to use `Multiwriter` for `io.stdout`? (currently, it's used only for stderr) That could help to me more informative during backup phase, so the progress gets reported throughout the whole process, not only at the end.

Doesn't the progress get reported during the backup? I can see the backup progress are being printed during backup.

**Comment by weisdd** [comment]
Then, I think, I'd make sense to move to `RESTIC_PROGRESS_FPS`, so you don't have to support a fork if that was the only reason to change something in restic.

> Doesn't the progress get reported during the backup? I can see the backup progress are being printed during backup.

Maybe something has changed since `v0.9.6-rc6`. I still use a fork of PG plugin from the time before it got re-licensed. There, all the backup progress is printed at once at the end of the backup phase.

**Comment by hossainemruz** [comment]
>Then, I think, I'd make sense to move to RESTIC_PROGRESS_FPS, so you don't have to support a fork if that was the only reason to change something in restic.

Yes. I am thinking the same.
