### ISSUE TITLE
Community Chart v2022.06.21 is broken

### ISSUE THREAD

**Issue by Legion2** [stashed/stash#1455]
`helm template appscode/stash --version v2022.06.21 --set features.community=true` produces invalid kubernetes yaml:
crd-installer job container image tag is missing: `image: "stashed/stash-crd-installer:"`

**Comment by Legion2** [comment]
I think this is because of this commit https://github.com/stashed/installer/commit/b92b8989a45044124a1b451093f240a825beb6d5 which removed the tag value from the values.yaml and used the Chart.yaml version, but missed to update all usages of the tag value.

**Comment by Legion2** [comment]
Workaround is to set `stash-community.operator.tag=v0.21.0`

**Comment by hossainemruz** [comment]
Thank you @Legion2 for identifying the issue. We are working on a fix.
