### ISSUE TITLE
time: unknown unit "d" in duration "2d"

### ISSUE THREAD

**Issue by sgielen** [stashed/stash#1480]
I created a `BackupConfiguration` with a `timeOut: 2d` -- the docs give a value of `5m` as an example so I had expected this to work.

The BackupConfiguration is initially accepted for creation and even becomes Ready. However, when a BackupSession is created, it fails and `kubectl describe backupsession` only indicates:

```
  Warning  Host Backup Failed  50s   Status Updater  backup failed for host "samba-0" of "StatefulSet"/"samba". Reason: failed to complete backup for host samba-0. Reason: FailedToInitializeBackendRepository
```

The stash logs describe the true reason:

```
E0919 18:07:10.294981       1 worker.go:93] Failed to process key samba/backup-1663610829. Reason: time: unknown unit "d" in duration "2d"
```

I have three possible suggestions for improving user experience on this point:

(1) Support `d` as a duration suffix for "days" (and also document it -- documentation currently doesn't say which suffixes are supported, it just gives "5m" as an example)
(2) Perform this validation on the BackupConfiguration instead of the BackupSession, so it comes up earlier
(3) Include the error message in the `kubectl describe` of the BackupConfiguration/BackupSession, so it comes up at the expected place instead of the more general "FailedToInitializeBackendRepository"

Thanks for your work on this application!

**Comment by hmsayem** [comment]
Thanks you @sgielen  pointing this out. `TimeOut` field expects a signed sequence of decimal numbers with optional fraction and unit suffix, like “100ms”, “2.3h” or “4h35m” and the valid time units are “ns”, “us” (or “µs”), “ms”, “s”, “m”, “h”. So, the validation should be performed on the `BackupConfiguration`. We are going to fix it.

**Comment by sgielen** [comment]
Looks like (2) and perhaps also (3) are fixed by https://github.com/stashed/stash/pull/1481 thanks :)

What would you like to do with (1)?

**Comment by hmsayem** [comment]
For the time being, we don't have any plan to support the `days` unit suffix. You have to use the equivalent hours instead.

**Comment by sgielen** [comment]
Thanks for the quick response & followup, in that case this is fixed!
