### ISSUE TITLE
ImagePullSecret is lost from a StatefulSet when the Stash sidecar is applied

### ISSUE THREAD

**Issue by ZeiP** [stashed/stash#1506]
I changed my application from a Deployment to StatefulSet per Digital Ocean's recommendation. After that the application pod the image of which is hosted on Amazon ECR started failing because of a Forbidden error. After a bit of digging I found out that after I created the StatefulSet, the imagePullSecrets is in place, but after a bit (when the Stash sidecar also starts showing up on ”kubectl get pod drupal-set-0 -o yaml”) imagePullSecrets is no longer there. If I remove the Backup configuration and recreate the StatefulSet, everything works ok. Is it possible that Stash removes the imagePullSecrets definition when it applies the sidecar?

**Comment by hmsayem** [comment]
Hello @ZeiP. Thank you for reporting the issue. We will investigate the issue further and get back to you.

**Comment by sgielen** [comment]
@ZeiP (disclaimer: I'm not a Stash developer, I'm a user who saw your bug report)

imagePullSecrets is a pod-level field, not a container-level field. So when Stash adds the sidecar container, it can only amend the imagePullSecrets of the Pod. Probably, the bug would be there, where the imagePullSecrets is replaced instead of amended. This gives a clue as to a workaround: if you add the same ImagePullSecret to your [BackupConfiguration](https://stash.run/docs/v2023.03.13/concepts/crds/backupconfiguration/) for now, that might allow the pull secret to remain in your StatefulSet allowing you to pull the private image as well as use Stash at the same time. Then once the issue is confirmed and resolved upstream, you can remove it from your BackupConfiguration again.

**Comment by ZeiP** [comment]
Thanks @sgielen! I tried adding runtimeSettings.pod.imagePullSecrets to the BackupConfiguration and at first it did seem to work – after a few redeployments the imagePullSecrets stayed in the configuration, the pod worked and I could even trigger the backup cron which worked. But now after I triggered the Backup cron the pod is again down and it seems to again be missing the imagePullSecrets configuration. So apparently also running the backup job removes it.

**Comment by sgielen** [comment]
That's strange, I never saw that happen. If you then remove and recreate the BackupConfiguration, is it back again? (Deleting and recreating the same BackupConfiguration should not invalidate any existing backups.)

That could be something interesting for the developers to look into, as well.

**Comment by ZeiP** [comment]
Just to be clear it had vanished from the pod configuration, it is still present in the backupconfiguration. Do you think removing and recreating the backupconfiguration could still work? I can definitely try if that might help, but it seems to me like the problem has more to do with the backup process fiddling something with the pod.

**Comment by sgielen** [comment]
Removing and recreating the backupconfiguration will cause the sidecar to be removed from the StatefulSet, and then subsequently readded, again overwriting the ImagePullSecrets. So I expect it will help, but at the cost of two restarts of the application, so it is not really a solution. It could help in figuring out when exactly the ImagePullSecrets are "lost" from the StatefulSet, though, which will help the Stash developers figure out what might trigger that bug.

**Comment by hmsayem** [comment]
Hello @ZeiP,  We have investigated the issue and it appears that the Stash replaces the existing `imagePullSecrets ` with the Stash-specific `imagePullSecrets` when it injects the sidecar and restarts the pod. We will update you as soon as it is resolved.

**Comment by hmsayem** [comment]
The issue with the `imagePullSecrets` in Stash has been fixed in the latest release. To test the fix, please upgrade Stash (v2023.03.20) to the latest version and let us know if it's working as expected. 

https://stash.run/docs/v2023.03.20/setup/upgrade/

**Comment by ZeiP** [comment]
I finally got around to updating and re-trying the backup configuration. It indeed seems to be working now, thanks!
