### ISSUE TITLE
License Verification Failed for community edition

### ISSUE THREAD

**Issue by cyrgimenv** [stashed/stash#1569]
Hello, I try to install following Stash Charts with default parameters in community mode, following [the installation instructions in the README](https://github.com/stashed/installer/tree/v2024.4.8/charts/stash-community):
`helm upgrade -i stash-community appscode/stash-community -n stash --create-namespace --version=v0.34.0`

Kubernetes version:
```
❯ kubectl version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.6-r0-25.4.22
```

The operator is failing, restarting and entering CrashLoopBackoff. Checking the logs:
```
E0419 08:42:37.747952       1 lib.go:170] Failed to verify license. Reason:  failed to read license: the server could not find the requested resource (post licenserequests.proxyserver.licenses.appscode.com)
```
also presents in kubernetes events:
```
86s         Warning   License Verification Failed   deployment/stash-community                Failed to verify license. Reason: failed to read license: the server could not find the requested resource (post licenserequests.proxyserver.licenses.appscode.com)
```

Is a license required to run the operator in community edition? I didn't expect it to be the case and I don't see any mention of it on the stash website.

**Comment by camrossi** [comment]
I just bumped in the same issue, there is a way to generate the license here: https://appscode.com/issue-license?p=stash

Installed the license and all is good!

**Comment by cyrgimenv** [comment]
I imagine this is the 30 day trial for the enterprise license, there is no community edition anymore:
https://appscode.com/blog/post/community-license/
Some information in the documentation and the README could save time here. I'm gonna close the ticket since the issue is answered.
