### ISSUE TITLE
Support PSP or SCC (openshift) enabled clusters

### ISSUE THREAD

**Issue by tamalsaha** [stashed/stash#462]
Use has cluster with PSP installed. Update Stash installer to support this.

Example PSP:
https://gist.github.com/tamalsaha/6599aa7d4603db056a2e22935e8ad37a

```
kubectl apply -f https://gist.githubusercontent.com/tamalsaha/6599aa7d4603db056a2e22935e8ad37a/raw/7c8b06a772657211ceaa08b04f5a79b959cca1bc/psp.yaml
```

**Comment by arjunsbabu** [comment]
Hi Team 
Another update. I have tried the recovery as per the link https://appscode.com/products/stash/0.7.0-rc.3/guides/restore/
In this case the recovery status phase have succeeded but the recovery havent happen

**Comment by tamalsaha** [comment]
@arjunsbabu , I am having trouble creating a PSP enabled cluster using kubeadm https://github.com/kubernetes/kubeadm/issues/791 . I need to be able to create a cluster first before I can fix this issue.

**Comment by tamalsaha** [comment]
- Get the PSP enabled minikube cluster
  - https://github.com/appscodelabs/tasty-kube/tree/master/minikube/psp

- Create PSP and add it to stash-sidecar ClusterRole
  - https://kubernetes.io/docs/concepts/policy/pod-security-policy/

- PSP for operator pods
  - https://github.com/kubedb/cli/pull/411/files?file-filters%5B%5D=.yaml
![operator-psp](https://user-images.githubusercontent.com/94814/54805212-7f0b4980-4c33-11e9-8c88-ec8ba8fb56a9.png)

- Add PSP name to RuntimeSettings (?)
  - Because use provided s/a
  - https://github.com/kubedb/cli/pull/415/files
  - https://github.com/kubedb/project/issues/343

**Comment by tamalsaha** [comment]
Discussion on PSP: https://www.youtube.com/watch?v=d3wEBtLXjaw
