### ISSUE TITLE
ApiServer Error: x509: certificate signed by unknown authority "svc-cat-ca"

### ISSUE THREAD

**Issue by mitchellmaler** [stashed/stash#560]
Deployed Stash with Helm and it seemed to work. I am seeing a lot of errors on the api server that I have provided below. The ca cert issuer in the api server is kube-ca so not sure why it has a cert for svc-cat-ca.

```
loading OpenAPI spec for "v1alpha1.repositories.stash.appscode.com" failed with: failed to retrieve openAPI spec, http error: ResponseCode: 503, Body: Error: 'x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "svc-cat-ca")'
```

When I deployed with helm I provided the ca string that is running the api server.
```
helm upgrade stash-operator appscode/stash --install
    --version 0.7.0
    --namespace stash
    --set apiserver.ca="[CA String]"
    --set apiserver.enableValidatingWebhook=true
    --set apiserver.enableMutatingWebhook=true
    --set rbac.create=true
```

**Comment by sebastien-prudhomme** [comment]
Same problem for me. The Helm chart is currently broken.

No need to setup the API server CA, but the API server need to know the CA used by Stash (the one that is generated by the Helm chart).

Will try to propose a fix.

**Comment by hossainemruz** [comment]
Try with the latest version. Feel free to reopen if not fixed.
