### ISSUE TITLE
Add doc explaining how to recover volume that was baked up by older version of stash

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#603]
As we have made some design changes in `Recovery` crd in stash 0.7.0 and introduced `Repository` crd. It is necessary to explain how to recover older snapshot with new stash.
- How to create Repository manually.

**Comment by farcaller** [comment]
Note: it's not only an older snapshot, it's also when you get a total cluser wipeout and want to start recovering the PVCs first
