### ISSUE TITLE
Enable to force delay deletion of Recovery job for debugging purpose.

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#615]
Sometimes Recovery failed and events are not enough to understand the failure reason. It will be great to see logs from recovery job. But, it is very hard to see log as job does not take much time to complete. So, we should add some mechanism to delay job completion.

**Comment by drazul** [comment]
As a workaround for now we can remove delete right for job resources on cluster role stash-operator

**Comment by hossainemruz** [comment]
Now, debugging is easy with `backupHistory` limit. By default Stash, keeps latest backup resources(job,BackupSession etc). You can configure it to keep as many as you want.
