### ISSUE TITLE
Configure environment variables (or proxy settings) on restic and recovery CRDs

### ISSUE THREAD

**Issue by drazul** [stashed/stash#621]
Hi there,
I'm trying to check the workflow for backup/recovery on my kubernetes cluster and I found a problem because my cluster is behind a proxy.

Because of that I need to be able to configure proxy settings for pods created by stash

**Comment by tamalsaha** [comment]
Fixed in v1beta1

**Comment by tamalsaha** [comment]
Add `Env` to `ContainerRuntimeSettings` ?

**Comment by tamalsaha** [comment]
Done.
