### ISSUE TITLE
FR: Add possibility to automatically restore a backup on deployment

### ISSUE THREAD

**Issue by Xnyle** [stashed/stash#633]
My use case is as follows:

1. Create Deployment, Restic, Recovery simultaneously.
2. If there is a backup taken for the respective Deployment, Stash should recover it (via init container). 
If no backup exist, nothing to do.
3. Then, Deployment starts.
4. Restic again takes backup of the Deployment.

I'm in need of this as I constantly destroy/reinstall deployments (on different clusters/arch) for testing purposes. Persistence is dynamically aligned via rook.
I'd like to have a general purpose solution that enables me to define that a certain PV is being recycled between deployments.
If I want to start over with fresh app data, I'd simply destroy the PV backup.

**Comment by hossainemruz** [comment]
Should be possible already in the latest releases.
