### ISSUE TITLE
Stash using high memory

### ISSUE THREAD

**Issue by pjaak** [stashed/stash#697]
Hi,

I have deployed stash into my kubernetes cluster to backup prometheus volumes. I have noticed stash is using 5gb+ memory is this normal?

Thanks

**Comment by pjaak** [comment]
+

**Comment by hossainemruz** [comment]
@pjaak 5gb+ memory usage is not expected. Can you provide any profiling data of Stash operator. Follow similar steps describe here: https://github.com/appscode/voyager/blob/master/docs/guides/ingress/monitoring/operator-profiling.md

**Comment by pjaak** [comment]
![Screen Shot 2019-03-15 at 9 05 03 am](https://user-images.githubusercontent.com/45154743/54394670-b04ebb80-4701-11e9-8333-4dc5e8d5b14e.png)

Its actually using 28gb on all my clusters and CPU spikes heaps when backups are getting created, is there GC or anything?? Is there a setting i need?

**Comment by pjaak** [comment]
![Screen Shot 2019-03-15 at 9 19 04 am](https://user-images.githubusercontent.com/45154743/54395256-74b4f100-4703-11e9-9098-76993759c84c.png)
I ran a top on the stash sidecar pod... Looks like 25252712K is getting cached on the pod memory which is 24GB roughly @hossainemruz

**Comment by pjaak** [comment]
![Screen Shot 2019-03-15 at 9 24 07 am](https://user-images.githubusercontent.com/45154743/54395816-05400100-4705-11e9-884f-f491dc25d8d9.png)

**Comment by hossainemruz** [comment]
That make sense. We didn't clean old cache. Thank you for figuring it out. We should cleanup cache after each backup. We are tracking this issue here: https://github.com/appscode/stash/issues/703

**Comment by pjaak** [comment]
Thanks @hossainemruz ill be watching the bug

**Comment by tamalsaha** [comment]
@pjaak , this issue is different from #703. 

From https://askubuntu.com/a/327115/167669,

> cached memory is used so that the HDD doesn't have to be read each time you open a file or a folder. So when you cache something it saves a disk read, that saves time and that's why Ubuntu caches as much as possible.
> 
> Having free memory isn't really good since it's not used, having cached memory will make access times shorter and improves performance. so the cached memory can be viewed as free memory since it's not actually used by any program it's just there to be as a backup of what could be used.
> 
> **Cached memory + free memory is the same as the available memory**, since the cached memory will be cleared if a program needs the space. So having lots of RAM will increase the performance of Ubuntu in general, especially if you are using programs with heavy RAM usage.

From https://github.com/kubernetes/kubernetes/issues/43916#issuecomment-430841267 and https://github.com/kubernetes/kubernetes/issues/43916#issuecomment-466041186

We need to set stash sidecar containers memory request and limit equal. This will prevent the container from being using too much cache memory.

**Comment by pjaak** [comment]
Okay no worries! @hossainemruz will wait for latest release

**Comment by tamalsaha** [comment]
TODO:
- [x] API support is ready https://github.com/kmodules/offshoot-api/blob/3386b694ec505dca686fd81f82c3be89e9ca5fda/api/v1/runtime_settings_types.go#L92
- [ ] Document that stash sidecar containers memory request and limit equal to handle this issue.
- [ ] Add test to confirm that setting is passed to sidecar correctly.
- [ ] Explore some default memory limit for restic sidecar (for future).

**Comment by hossainemruz** [comment]
Last todo is being  tracked in the Zoho backlog.
