### ISSUE TITLE
401 creating repositories on B2

### ISSUE THREAD

**Issue by ndarilek** [stashed/stash#698]
Using Stash 0.8.3 and am getting the following in my Stash sidecar logs:

```
E0311 22:17:39.640287       1 restic.go:204] Error running command '/bin/restic [snapshots --json --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic snapshots --json --cache-dir /tmp/restic-cache
Fatal: unable to open repo at b2:thewordnerd-syncthing:/deployment/syncthing: b2.NewClient: b2_authorize_account: 401: 
E0311 22:17:41.036792       1 restic.go:204] Error running command '/bin/restic [init --cache-dir /tmp/restic-cache]' output:
[golang-sh]$ /bin/restic init --cache-dir /tmp/restic-cache
Fatal: create repository at b2:thewordnerd-syncthing:/deployment/syncthing failed: b2.NewClient: b2_authorize_account: 401: 
I0311 22:17:41.040376       1 recorder.go:82] Event created:  stash.158b076cf0ca0566
```

Initially I set my account ID to my master account ID. This was wrong, so I changed that to the application key ID of the key I was using. No change. I've deleted and recreated the secret a couple times, checked to ensure that the key/ID matches, ensured the files are only a single line, etc.

I'm looking at [this issue](https://github.com/restic/restic/issues/1923) which suggests this may have changed. Looks like the container is using Restic 0.8.0, which is a bit old, and definitely not the 0.9.3 documented.

I'm wondering if the B2 API has changed since Restic v0.8.0, and if it might be worth an upgrade of the binary to see if that's the issue here?

Thanks.

**Comment by hossainemruz** [comment]
@ndarilek did you tried this workaround? https://github.com/restic/restic/issues/1923#issuecomment-410037036

**Comment by ndarilek** [comment]
Are you asking what I set the application/account ID to? Tried both the 
master with a master application key, and the application key ID/secret. 
No luck.

**Comment by hossainemruz** [comment]
Ok. Then, we need to take a look. We will update you if we find anything.

**Comment by ndarilek** [comment]
According to a reply on the previously-linked Restic issue, the 
Backblaze API changed in 2018, and Restic was updated to match. It looks 
like the containers are running Restic 0.8.0, which was released in 
2017. So this is probably broken until the upgrade.


I see an outstanding issue to upgrade Restic. Is there a timeline on 
that? It looks like an upgrade will break backwards-compatibility. 
Should I be using Stash at this time? I'm wondering if I'll have to wipe 
out my existing backups and start over when a new version is released.


Thanks.

**Comment by hossainemruz** [comment]
Try with latest version. Feel free to reopen if not fixed
