### ISSUE TITLE
Stash v1beta1 documentation

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#706]
## Welcome

 - [x] Home
	- [x] Stash Features
- [x] Changelog (same as current)
- [x] Contributing (same as current. maybe improve in future)
- [x] Roadmap (same as current)
- [x] Acknowledgement(same as current)
- [x] Support (same as current)
- [ ] Known issue
	- Specify the scenario where stash will fail

## Concept
- [x] Stash Architecture
- [x] Declarative API
	- [x] Repository
	- [x] BackupConfiguration
	- [x] BackupSession
	- [x] RestoreSession
	- [x] BackupConfigurationTemplate
	- [x] Function
	- [x] Task
	- [x] AppBinding
	- [x] Snapshot
- [x] Old API
	- Restic
	- Recovery

## Setup
- [ ] Install
	- [ ] Add requirements section before installation process.
		- extension apiserver support
		- webhook support
		- link to required rbac permission doc.
		- link to cluster specific requirement (i.e. GKE)
- [x] Upgrade (this doc is old. need update)
- [x] Uninstall (same as current)
- [ ] RBAC (move RBAC guide from guide to setup)
- [ ] Developer Guide
	- [ ] Overview of Stash repo structure
	- [ ] Building & Testing guide (already exist. just update to recent developement)
	- [x] Release (same as current) 

## Guides

- [x] Supported Backends (same as current)
	- [x] Add REST backend doc
	- [x] Update docs according new api

- [x] Workloads
	- [x] How backup & restore works?
	- [x] Backup & Restore Deployment
	- [x] Backup & Restore StatefulSet
	- [x] Backup & Restore DaemonSet
	- [ ] Backup & Restore DeploymentConfig
	- [ ] Backup & Restore ReplicaSet
	- [ ] Backup & Restore ReplicationController

- [x] Stand-alone Volumes
  - [x] How backup & restore works?
  - [x] Backup & Restore PVC

- [x] Databases
	- [x] How backup & Restore works?
	- [x] Backup & Restore PostgreSQL
	- [x] Backup & Restore MySQL
	- [x] Backup & Restore MongoDB
	- [x] Backup & Restore Elasticsearch

- [ ] Cluster Resources
	- [ ] How backup & restore works?
	- [ ] Backup & Restore cluster YAMLs

- [x] Volume Snapshot
  - [x] How volume snapshot works?
  - [x] How restore from snapshot works?
  - [x] Backup & Restore Deployment's volumes
  - [x] Backup & Restore StatefulSet's volume
	- Backup:
	  - [x] Backup all PVC.
	  - [x] Backup single PVC.
	  - Restore:
	  - [x] Restore from different VolumeSnapshot
	  - [x] Restore from same VolumeSnapshot
  - [x] Backup & Restore standalone PVC.

- [x] Auto Backup
	- [x] How default backup works?
	- [x] Backup workload
	- [x] Backup pvc
	- [x] Backup database

- [ ] Advance Use Case
	- [x] Instant backup
	- [ ] Restore from different namespace
	- [ ] Restore in different cluster
	- [x] Restore in PVC template
	- [ ] Backup custom database

- [ ] Platforms (same as current. just update according to new api)
	- [x] EKS
	- [x] AKS
	- [x] GKE
	- [x] Minio
	- [x] Rook
	- [ ] OpenShift

- [x] Monitoring (update according to new metrics)
	- [x] How monitoring works?
	- [x] Builtin Prometheus
	- [x] CoreOS operator
	- [ ] Grafana Dashboard

- [x] Stash CLI

- [ ] Troubleshooting
	- [ ] Backup
	- [ ] Restore

**Comment by tamalsaha** [comment]
- [ ] Document that discusses the differences between v1alpha1 and v1beta1 apis. For example, there will be only one repository per workload.

**Comment by tamalsaha** [comment]
- [ ] OpenShift DeploymentConfig

**Comment by tamalsaha** [comment]
- [ ] ReplicaSet
- [ ] ReplicationController

**Comment by tamalsaha** [comment]
- [ ] Search and replace direct links to our website https://appscode.com/products/stash/0.8.3/
 - [ ] Check advance-use-case folder has been renamed and moved properly.

**Comment by tamalsaha** [comment]
- [ ] Do we still have the pause feature? I do not remember seeing doc for that.

**Comment by tamalsaha** [comment]
For later:
- [ ] Share Blueprint between different types of database.

**Comment by tamalsaha** [comment]
- [ ] How to stop backup?
  - Delete backup config
  - Delete annotation in case of AutoBackup

**Comment by hossainemruz** [comment]
Relevant requirements are being tracked in Zoho backlog.
