### ISSUE TITLE
Handle restored files permission properly

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#733]
Stash does not preserve permissions of original files after restore. We must add documentation explaining when file permission get changed and how user can configure stash to avoid this.

Here, is a summary of file permissions modification in different backup and restore scenarios:

## Backup and Restore Behaviour

| Case  | Original File Owner | Backup `sidecar` User | Backup Succeed? | Restore `init-container` User | Restore Succeed? | Restored File Owner | Editable to Original Owner? |
| :---: | :-----------------: | :-------------------: | :-------------: | :---------------------------: | :--------------: | :-----------------: | :-------------------------: |
|   1   |        root         |     stash (1005)      |    &#10003;     |          stash(1005)          |     &#10003;     |        1005         |          &#10003;           |
|   2   |        2000         |      stash(1005)      |    &#10003;     |          stash(1005)          |     &#10003;     |        1005         |          &#10007;           |
|   3   |        2000         |         root          |    &#10003;     |             root              |     &#10003;     |        2000         |          &#10003;           |
|   4   |        2000         |         root          |    &#10003;     |          stash(1005)          |     &#10007;     |          -          |              -              |
|   5   |        2000         |         3000          |    &#10003;     |          stash(1005)          |     &#10007;     |          -          |              -              |
|   6   |        2000         |         3000          |    &#10003;     |             root              |     &#10003;     |        2000         |          &#10003;           |
|   7   |        2000         |         3000          |    &#10003;     |             3000              |     &#10003;     |        3000         |          &#10007;           |

**Comment by tamalsaha** [comment]
http://man7.org/linux/man-pages/man7/capabilities.7.html

`CAP_CHOWN`

**Comment by hossainemruz** [comment]
Fixed in this PR: https://github.com/stashed/stash/pull/729
