### ISSUE TITLE
Question about Backup behavior

### ISSUE THREAD

**Issue by devdattakulkarni** [stashed/stash#743]
Hello,

We are using this Operator in our setup. We use it to take backup of a Custom Resource volume (Moodle). The exact steps can be found at following link:

https://github.com/cloud-ark/kubeplus/blob/master/examples/moodle-presslabs-stash/steps.txt

In order to take backup of the Volume used by Moodle Custom Resource instance, we first find out the created Deployment, give it some label, and then create the Restic Custom Resource instance with the corresponding label selector and the volume name. The definition of Restic Custom Resource can be found at this link:

https://github.com/cloud-ark/kubeplus/blob/master/examples/moodle-presslabs-stash/moodle-backup/restic-moodle.yaml

We are noticing following behavior when trying to take backup of the Volume.
- The moodle Custom Resource instance gets terminated and then re-created. This seems strange. 

I was wondering if you can shed some light on how does the backup work? Does it terminate the Deployment object corresponding to the Volume for which the backup is being taken?

We are using latest Stash Operator chart to install Stash.

**Comment by hossainemruz** [comment]
@devdattakulkarni when Stash find a target, it inject a sidecar container. If any change happen in `spec.podTemplate` section of a Deployment, it restart. Thus, when Stash inject a sidecar container, old pods get terminated and new pods starts with the injected sidecar.

**Comment by devdattakulkarni** [comment]
@hossainemruz Thanks for the clarification. Ok, I understand why the Pod gets restarted.

One issue with this approach though is that there is downtime experienced in the application (previous Pod is terminated and new Pod is started back up). Are there any thoughts/ideas around taking backup without using a sidecar?

**Comment by hossainemruz** [comment]
@devdattakulkarni we have added standalone volume backup option in master (not yet released). This enables to take backup PVC without injecting sidecar to respective workload. This will let you backup without down time. However, your PVC must be mountable to multiple workload simultaneously.

**Comment by devdattakulkarni** [comment]
@hossainemruz Cool! Will look forward to the next release. 
Is there a specific Spec attribute in PVC that we need to set to make it mountable in multiple workloads?

**Comment by hossainemruz** [comment]
Yes. Access mode of PVC should support mounting in multiple pod.
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by devdattakulkarni** [comment]
Ok. So we will need to use Kubernetes 1.13 and configure PV with ReadOnlyMany. Currently we use HostPath. Will that continue to work with the new backup approach and above setting?

**Comment by hossainemruz** [comment]
>Will that continue to work with the new backup approach and above setting?

No. We are re-designing Stash to support those use-cases. Stand alone PVC backup is supported by new design which utilize new API. However, your old settings for backup and recovery will still work but you won't able to use new features.

**Comment by hossainemruz** [comment]
Stash `0.9.0-rc.x` should support the use cases you mentioned. If it does not, feel free to reopen.
