### ISSUE TITLE
unable to take the EKS -PVC backup in 8.3.0 using Stash 

### ISSUE THREAD

**Issue by dsreddy99** [stashed/stash#757]
Hi Team ,

I am unable to take the back of the running pods -Pvc using stash .8.3

The repository is not getting created .
The sidecar is getting created but unable to moun to the volume it seems.

I dont see the snapshot crd in the crd list .

Please help in this case and let me know how to proceed further .

Thanking you 
Best regards,
Satish

**Comment by hossainemruz** [comment]
@dsreddy99 can you please show the YAML for the workload you are trying to backup? Also share YAML for `Restic`.

**Comment by hossainemruz** [comment]
Please try with Stash `0.9.0-rc.2`. If you still face this problem, feel free to reopen.
