### ISSUE TITLE
BackupSession naming format

### ISSUE THREAD

**Issue by tamalsaha** [stashed/stash#791]
Can we use the format that CronJobs use to generate names for Jobs for a CronJob; eg, backupconfig-{TIMESTAMP _ upto sec?}

https://github.com/stashed/stash/pull/739#discussion_r283554604

**Comment by tamalsaha** [comment]
https://github.com/kubernetes/kubernetes/blob/81a61ae0e37143299ee5947a6c2c5195ec5f72ae/pkg/controller/cronjob/utils.go#L156

**Comment by hossainemruz** [comment]
Fixed in #797
