### ISSUE TITLE
Stash v1beta1 enhancement 

### ISSUE THREAD

**Issue by hossainemruz** [stashed/stash#840]
- [ ] Template version part of `BackupBlueprint`'s name field so that same `BackupBlueprint` can be used to backup all database version. [Emruz]
	- https://github.com/stashed/docs/pull/17#discussion_r306444544
- [x] Explain `VolumeMounts` field [Sagor]
	- https://github.com/stashed/docs/pull/7#discussion_r305578188
- [x] Rename `directories` to `paths` [Sagor]
	- https://github.com/stashed/docs/pull/12#discussion_r305610926
- [x] Use short name for automatically created Repository and BackupConfiguration?
	- https://github.com/stashed/docs/pull/8#discussion_r305591170
- [ ] Make waiting time to finish VolumeSnapshot configurable
		- https://github.com/stashed/stash/pull/787#discussion_r286824788
- [ ] Add unit test for validators
	- https://github.com/stashed/stash/pull/795#discussion_r286380544
- [ ] Add example of how to write AppBinding manually for each supported databases. [Emruz]
	- https://github.com/stashed/stash/pull/739#discussion_r283165872
- [ ] Explain when retentionPolicy is applied
	- https://github.com/stashed/stash/pull/739#discussion_r283527566
- [x] Clarify that status field for `RestoreSession` is only available for `driver: Restic`. [Sagor]
	- https://github.com/stashed/stash/pull/739#discussion_r283563957
- [x] Clarify that Stash restore data in absolute path. Hence, the restored volume must be mounted in the same directory as the original volume. [Sagor]
- [x] Clarify that GCS backend needs Storage Object Admin role.
	- https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#google-cloud-storage [Emruz]
- [x] Add document for pause backup [Sagor]
- [x] Clone PVC: Explain that `volumeMounts.name` must be same as volumeClaimTemplate name without the `POD_ORDINAL` part. [Sagor]
- [x] Explain the backup strategy for Deployment,ReplicaSet,ReplicationController(only single pod. uses leader election), StatefulSet(all pods), DaemonSet(all pod). [Emruz]
- [x] Stop taking backup of old target to avoid locking issue while restore (doc). [Emruz]

**Comment by tamalsaha** [comment]
- [ ] Check advance-use-case folder has been renamed and moved properly.

**Comment by tamalsaha** [comment]
- [ ] Suspend Cronjob for paused backup? https://github.com/stashed/docs/pull/21#discussion_r310259014

**Comment by tamalsaha** [comment]
- [ ] Volume snapshot based backup doc is missing for stash-mongodb

**Comment by tamalsaha** [comment]
- [ ] apply secret transformations in AppBinding
- [ ] Document that VolumeSnapshot feature in alpha in K8s and should not be used for production.

**Comment by hossainemruz** [comment]
Respective items are being tracked in Zoho project.
