### ISSUE TITLE
Failing to create snapshot resource

### ISSUE THREAD

**Issue by codejamninja** [stashed/stash#860]
Stash is backing up my data just fine, but it fails to create the snapshot resource, so I can't restore any of my data. I have kubedb installed, and I noticed that kubedb has a resource kind called snapshot. Is it possible that they are colliding with each other?

**Comment by hossainemruz** [comment]
>but it fails to create the snapshot resource

What error are you getting? Snapshot is not a crd for Stash. It is handled by Stash Extended API Server.

**Comment by codejamninja** [comment]
I guess I'm a little confused about how it works. Your documentation says `Snapshot` is a CRD.

![Screenshot from 2019-08-06 23-13-00](https://user-images.githubusercontent.com/6234038/62594319-d25afd00-b89f-11e9-97ab-40f9332f7e52.png)

**Comment by codejamninja** [comment]
How do I tell `Recovery` what snapshot to restore? The docs seem to suggest that I reference a `Snapshot` resource.

![Screenshot from 2019-08-06 23-14-30](https://user-images.githubusercontent.com/6234038/62594373-10f0b780-b8a0-11e9-9305-cf8034557867.png)

**Comment by hossainemruz** [comment]
Try
```
kubectl get snapshots.repositories.stash.appscode.com

```

**Comment by codejamninja** [comment]
Ah, ok. It worked. Thanks.

How would I install the latest version of stash? I was to install version `0.9.0`.

**Comment by hossainemruz** [comment]
0.9.0 is not out yet.

**Comment by codejamninja** [comment]
Ok thanks
