### ISSUE TITLE
[feature] clean up objects

### ISSUE THREAD

**Issue by segator** [stashed/stash#867]
Yesterday I tried stash for first time,  configured auto backup for PVC, and works  perfect!
But I saw it creates lot of objects, backupconfiguration, backupsession, empty cronjobs, jobs..

What I expect is after a period of time stash should delete this backup references(BackupSessions).

And If I delete the backupSession object it delete this snapshot from the repository?

**Comment by hossainemruz** [comment]
>What I expect is after a period of time stash should delete this backup references(BackupSessions).

We are going to clean up old BackupSession automatically according to the retention policy.

>And If I delete the backupSession object it delete this snapshot from the repository?

No

**Comment by segator** [comment]
I did some tests, the backupsession is deleted but the job asociated not, if I try to delete it kubectl delete backupsession xxxxxxxxxxxxx, is the same case. Is so ugly see all the objects created through rancher UI, a cronjob for every volume, but no tasks inside, and then a individual job success or failed but stuck there forever.

![image](https://user-images.githubusercontent.com/2348131/63042020-6f81eb00-bec9-11e9-8b9f-a9f789b4113b.png)

![image](https://user-images.githubusercontent.com/2348131/63042040-7d377080-bec9-11e9-8bcd-055091fe822c.png)

**Comment by hossainemruz** [comment]
>When I start the node where the volumen exist, what is going to happens? it will try to execute the 4 tasks in parallel? this can be a mess for a backup!

Yes. However, only one of them will take backup and others will complete without taking backup.

**Comment by hossainemruz** [comment]
This issue should be fixed by #907 and will be available in `0.9.0-rc.1` release.
