### ISSUE TITLE
subPath stash autobackup annotation

### ISSUE THREAD

**Issue by codejamninja** [stashed/stash#868]
How do I annotate a subPath in a stash auto backup?

```
stash.appscode.com/volume-mounts: "source-data-1:/source/data-1,source-data-2:/source/data-2"
```

Here is a proposed suggestion in case you don't support it.

```
stash.appscode.com/volume-mounts: "source-data-1@/some/subpath:/source/data-1,source-data-2@/another/subpath:/source/data-2"
```

**Comment by hossainemruz** [comment]
@codejamninja Thank you for noticing this. We are going to use the following format:

```
stash.appscode.com/volume-mounts: "<volume 1 name>:<mount path>:<sub path>,<volume 2 name>:<mount path>"
```

**Comment by codejamninja** [comment]
@hossainemruz ok, sounds great. Is it already implemented? If not, is there an issue where I can track the progress?

**Comment by hossainemruz** [comment]
Working on this. It will be available in `rc.1`.
