### ISSUE TITLE
Cannot pull image stashed/stash-mysql:8.0.14

### ISSUE THREAD

**Issue by codejamninja** [stashed/stash#879]
I am getting the following error when trying to backup mysql.

```
Failed to pull image "stashed/stash-mysql:8.0.14": rpc error: code = Unknown desc = Error response from daemon: manifest for stashed/stash-mysql:8.0.14 not found
```

The `stashed/stash-mysql` docker image seems to be missing the `8.0.14` tag.

https://hub.docker.com/r/stashed/stash-mysql/tags

**Comment by hossainemruz** [comment]
@codejamninja We haven't pushed the docker image yet. Those are outdated image. We now use docker manifest to build image for multiple architecture. These update hasn't been pushed to other repo other than postgres.

**Comment by hossainemruz** [comment]
Not today. We need to make some changes. We are making `stashed/postgres` ready first. Then, all other repo will follow it's template.

**Comment by codejamninja** [comment]
No prob. I am just pushing the containers to my dockerhub for now.

https://hub.docker.com/r/codejamninja/stash-postgres
