### ISSUE TITLE
Add preBackup & postBackup hooks in BackupConfiguration

### ISSUE THREAD

**Issue by tamalsaha** [stashed/stash#885]
We add something like https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#define-poststart-and-prestop-handlers

in BackupConfiguration

**Comment by muff1nman** [comment]
The preBackup and postBackup are currently not hooked up, correct? Will these be usable for the sidecare model?

**Comment by hossainemruz** [comment]
From: https://github.com/stashed/stash/pull/978#issuecomment-557964423
>Can an option be added on the backup post hook to always run, even if the backup job fails?

>Use case is that my workload automatically flushes to its mounted pvc. I'd like to do pause/resume autoflush as pre/post hooks, but need to ensure that the resume post hook always turns automatic flushing back on.

@tamalsaha what do you think? Seems to be a valid use-case.

**Comment by hossainemruz** [comment]
Done in #978
