### ISSUE TITLE
Generate swagger.json for v1beta1

### ISSUE THREAD

**Issue by benosman** [stashed/stash#896]
It would be helpful for me if there was an up to date version of swagger.json containing the new v1beta1 resources.

Currently the swagger.json was last modified in May 2019
https://github.com/stashed/stash/blob/master/api/openapi-spec/swagger.json

I notice the `generateSwaggerJson()` function call is commented out here:
https://github.com/stashed/stash/blob/88c84275f20984393cd8e2be0007f0e55f654ab4/hack/gencrd/main.go#L142

**Comment by tamalsaha** [comment]
How are you using the swagger.json?

**Comment by benosman** [comment]
I'm using the swagger.json with [pulumi](https://github.com/pulumi/pulumi), an infrastructure as code tool. (similar to terraform).

Using a code gen tool, the swagger.json helps me build a 'provider' (a wrapper around your schemas) to automate the creation/modification of stash resources.
