### ISSUE TITLE
[0.9.0-rc.0] Cannot list snapshots

### ISSUE THREAD

**Issue by michaelkoetter** [stashed/stash#901]
Backups seem to be created, but when I try to list snapshots there is an error:

```bash
kubectl get snapshots -n plexmediaserver                        
# Error from server (InternalError): Internal error occurred: could not execute: command terminated with exit code 126, reason: 
```

I think it is because stash tries to execute `/bin/stash` in the sidecar, which doesn't exist (instead it seems to be just `/stash`):

```
I0915 10:59:32.479571       1 utils.go:217] Executing command [/bin/stash snapshots --repo-name=deployment.plexmediaserver] on pod plexmediaserver-6fc577bdd5-tqk7f
```

Manually running the command with `/stash` seems to work

```bash
kubectl -n plexmediaserver exec -it plexmediaserver-6fc577bdd5-tqk7f -c stash -- /stash snapshots --repo-name=deployment.plexmediaserver
```

**Comment by hossainemruz** [comment]
@michaelkoetter Thank you for reporting. It should be fixed by this PR: https://github.com/stashed/stash/pull/902
