### ISSUE TITLE
Stash operator deployment failed to be ready

### ISSUE THREAD

**Issue by DineshC001** [stashed/stash#913]
I am trying to install stash using the script but the operatorcontainer does not start:

/stash.sh --docker-registry=combined-registry.sbx.zone/appscode --namespace=stash --enable-validating-webhook=false --enable-mutating-webhook=false
checking kubeconfig context
xxx-tools

Downloading onessl ...
checking whether extended apiserver feature is enabled

STASH_BYPASS_VALIDATING_WEBHOOK_XRAY=false
STASH_DOCKER_REGISTRY=combined-registry.sbx.zone/appscode
STASH_ENABLE_ANALYTICS=true
STASH_ENABLE_APISERVER=false
STASH_ENABLE_MUTATING_WEBHOOK=false
STASH_ENABLE_STATUS_SUBRESOURCE=true
STASH_ENABLE_VALIDATING_WEBHOOK=false
STASH_IMAGE_PULL_POLICY=IfNotPresent
STASH_IMAGE_PULL_SECRET=
STASH_IMAGE_TAG=v0.9.0-rc.0
STASH_NAMESPACE=stash
STASH_PRIORITY_CLASS=
STASH_PURGE=0
STASH_RUN_ON_MASTER=0
STASH_SERVICE_ACCOUNT=stash-operator
STASH_SERVICE_NAME=stash-operator
STASH_UNINSTALL=0
STASH_USE_KUBEAPISERVER_FQDN_FOR_AKS=true
STASH_WEBHOOK_SIDE_EFFECTS=sideEffects: None

Wrote ca certificates in  /Users/xxxxx/Documents/git/devops-ansible-rancher/xxx-helm-charts/installer/deploy
Wrote server certificates in  /Users/xxxxx/Documents/git/devops-ansible-rancher/xxx-helm-charts/installer/deploy
deployment.apps/stash-operator created
secret/stash-apiserver-cert created
service/stash-operator created
serviceaccount/stash-operator created
clusterrole.rbac.authorization.k8s.io/stash-operator reconciled
	reconciliation required create
	missing rules added:
		{Verbs:[*] APIGroups:[apiextensions.k8s.io] Resources:[customresourcedefinitions] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get patch] APIGroups:[apiregistration.k8s.io] Resources:[apiservices] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[delete get list watch patch] APIGroups:[admissionregistration.k8s.io] Resources:[mutatingwebhookconfigurations validatingwebhookconfigurations] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[*] APIGroups:[stash.appscode.com] Resources:[*] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[*] APIGroups:[appcatalog.appscode.com] Resources:[*] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get list watch patch] APIGroups:[apps] Resources:[daemonsets deployments replicasets statefulsets] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get list watch create delete patch] APIGroups:[batch] Resources:[jobs cronjobs] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get list watch patch] APIGroups:[] Resources:[namespaces replicationcontrollers] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[create update get delete] APIGroups:[] Resources:[configmaps] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get list watch create patch] APIGroups:[] Resources:[persistentvolumeclaims] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get] APIGroups:[] Resources:[secrets services] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[create] APIGroups:[] Resources:[events] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[list] APIGroups:[] Resources:[nodes] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get create list delete deletecollection] APIGroups:[] Resources:[pods pods/exec] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get create patch delete] APIGroups:[] Resources:[serviceaccounts] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get create delete patch] APIGroups:[rbac.authorization.k8s.io] Resources:[clusterroles roles rolebindings clusterrolebindings] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get list watch patch] APIGroups:[apps.openshift.io] Resources:[deploymentconfigs] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[use] APIGroups:[policy] Resources:[podsecuritypolicies] ResourceNames:[stash-operator-psp stash-backupsession-cron stash-backup-job stash-restore-job] NonResourceURLs:[]}
		{Verbs:[create get list watch patch] APIGroups:[snapshot.storage.k8s.io] Resources:[volumesnapshots volumesnapshotcontents volumesnapshotclasses] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get] APIGroups:[storage.k8s.io] Resources:[storageclasses] ResourceNames:[] NonResourceURLs:[]}
clusterrolebinding.rbac.authorization.k8s.io/stash-operator reconciled
	reconciliation required create
	missing subjects added:
		{Kind:ServiceAccount APIGroup: Name:stash-operator Namespace:stash}
rolebinding.rbac.authorization.k8s.io/stash-apiserver-extension-server-authentication-reader reconciled
	reconciliation required create
	missing subjects added:
		{Kind:ServiceAccount APIGroup: Name:stash-operator Namespace:stash}
clusterrolebinding.rbac.authorization.k8s.io/stash-apiserver-auth-delegator reconciled
	reconciliation required create
	missing subjects added:
		{Kind:ServiceAccount APIGroup: Name:stash-operator Namespace:stash}
clusterrole.rbac.authorization.k8s.io/appscode:stash:edit reconciled
	reconciliation required create
	missing rules added:
		{Verbs:[*] APIGroups:[stash.appscode.com] Resources:[restics recoveries repositories] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[delete deletecollection get list] APIGroups:[repositories.stash.appscode.com] Resources:[snapshots] ResourceNames:[] NonResourceURLs:[]}
clusterrole.rbac.authorization.k8s.io/appscode:stash:view reconciled
	reconciliation required create
	missing rules added:
		{Verbs:[get list watch] APIGroups:[stash.appscode.com] Resources:[restics recoveries repositories] ResourceNames:[] NonResourceURLs:[]}
		{Verbs:[get list] APIGroups:[repositories.stash.appscode.com] Resources:[snapshots] ResourceNames:[] NonResourceURLs:[]}
Applying Pod Sucurity Policies
podsecuritypolicy.policy/stash-operator-psp created
podsecuritypolicy.policy/stash-backupsession-cron created
podsecuritypolicy.policy/stash-backup-job created
podsecuritypolicy.policy/stash-restore-job created

waiting until stash operator deployment is ready
timed out waiting for the condition
Stash operator deployment failed to be ready

The logs from the operator container 
I1003 16:23:56.198392       1 log.go:172] FLAG: --alsologtostderr="false"
I1003 16:23:56.198471       1 log.go:172] FLAG: --audit-dynamic-configuration="false"
I1003 16:23:56.198486       1 log.go:172] FLAG: --audit-log-batch-buffer-size="10000"
I1003 16:23:56.198500       1 log.go:172] FLAG: --audit-log-batch-max-size="1"
I1003 16:23:56.198516       1 log.go:172] FLAG: --audit-log-batch-max-wait="0s"
I1003 16:23:56.198539       1 log.go:172] FLAG: --audit-log-batch-throttle-burst="0"
I1003 16:23:56.198564       1 log.go:172] FLAG: --audit-log-batch-throttle-enable="false"
I1003 16:23:56.198586       1 log.go:172] FLAG: --audit-log-batch-throttle-qps="0"
I1003 16:23:56.198605       1 log.go:172] FLAG: --audit-log-format="json"
I1003 16:23:56.198619       1 log.go:172] FLAG: --audit-log-maxage="0"
I1003 16:23:56.198635       1 log.go:172] FLAG: --audit-log-maxbackup="0"
I1003 16:23:56.198648       1 log.go:172] FLAG: --audit-log-maxsize="0"
I1003 16:23:56.198664       1 log.go:172] FLAG: --audit-log-mode="blocking"
I1003 16:23:56.198681       1 log.go:172] FLAG: --audit-log-path="-"
I1003 16:23:56.198697       1 log.go:172] FLAG: --audit-log-truncate-enabled="false"
I1003 16:23:56.198724       1 log.go:172] FLAG: --audit-log-truncate-max-batch-size="10485760"
I1003 16:23:56.198738       1 log.go:172] FLAG: --audit-log-truncate-max-event-size="102400"
I1003 16:23:56.198752       1 log.go:172] FLAG: --audit-log-version="audit.k8s.io/v1"
I1003 16:23:56.198768       1 log.go:172] FLAG: --audit-policy-file=""
I1003 16:23:56.198803       1 log.go:172] FLAG: --audit-webhook-batch-buffer-size="10000"
I1003 16:23:56.198817       1 log.go:172] FLAG: --audit-webhook-batch-initial-backoff="10s"
I1003 16:23:56.198832       1 log.go:172] FLAG: --audit-webhook-batch-max-size="400"
I1003 16:23:56.198848       1 log.go:172] FLAG: --audit-webhook-batch-max-wait="30s"
I1003 16:23:56.198886       1 log.go:172] FLAG: --audit-webhook-batch-throttle-burst="15"
I1003 16:23:56.198903       1 log.go:172] FLAG: --audit-webhook-batch-throttle-enable="true"
I1003 16:23:56.198917       1 log.go:172] FLAG: --audit-webhook-batch-throttle-qps="10"
I1003 16:23:56.198930       1 log.go:172] FLAG: --audit-webhook-config-file=""
I1003 16:23:56.198944       1 log.go:172] FLAG: --audit-webhook-initial-backoff="10s"
I1003 16:23:56.198959       1 log.go:172] FLAG: --audit-webhook-mode="batch"
I1003 16:23:56.198972       1 log.go:172] FLAG: --audit-webhook-truncate-enabled="false"
I1003 16:23:56.198985       1 log.go:172] FLAG: --audit-webhook-truncate-max-batch-size="10485760"
I1003 16:23:56.198999       1 log.go:172] FLAG: --audit-webhook-truncate-max-event-size="102400"
I1003 16:23:56.199017       1 log.go:172] FLAG: --audit-webhook-version="audit.k8s.io/v1"
I1003 16:23:56.199030       1 log.go:172] FLAG: --authentication-kubeconfig=""
I1003 16:23:56.199046       1 log.go:172] FLAG: --authentication-skip-lookup="false"
I1003 16:23:56.199062       1 log.go:172] FLAG: --authentication-token-webhook-cache-ttl="***REDACTED***"
I1003 16:23:56.199078       1 log.go:172] FLAG: --authentication-tolerate-lookup-failure="false"
I1003 16:23:56.199096       1 log.go:172] FLAG: --authorization-always-allow-paths="[]"
I1003 16:23:56.199113       1 log.go:172] FLAG: --authorization-kubeconfig=""
I1003 16:23:56.199128       1 log.go:172] FLAG: --authorization-webhook-cache-authorized-ttl="10s"
I1003 16:23:56.199143       1 log.go:172] FLAG: --authorization-webhook-cache-unauthorized-ttl="10s"
I1003 16:23:56.199160       1 log.go:172] FLAG: --bind-address="0.0.0.0"
I1003 16:23:56.199176       1 log.go:172] FLAG: --burst="100"
I1003 16:23:56.199192       1 log.go:172] FLAG: --bypass-validating-webhook-xray="false"
I1003 16:23:56.199252       1 log.go:172] FLAG: --cert-dir="apiserver.local.config/certificates"
I1003 16:23:56.199271       1 log.go:172] FLAG: --client-ca-file=""
I1003 16:23:56.199287       1 log.go:172] FLAG: --contention-profiling="false"
I1003 16:23:56.199303       1 log.go:172] FLAG: --docker-registry="combined-registry.sbx.zone/appscode"
I1003 16:23:56.199319       1 log.go:172] FLAG: --enable-analytics="true"
I1003 16:23:56.199335       1 log.go:172] FLAG: --enable-mutating-webhook="false"
I1003 16:23:56.199348       1 log.go:172] FLAG: --enable-status-subresource="true"
I1003 16:23:56.199361       1 log.go:172] FLAG: --enable-swagger-ui="false"
I1003 16:23:56.199374       1 log.go:172] FLAG: --enable-validating-webhook="false"
I1003 16:23:56.199389       1 log.go:172] FLAG: --help="false"
I1003 16:23:56.199420       1 log.go:172] FLAG: --http2-max-streams-per-connection="1000"
I1003 16:23:56.199434       1 log.go:172] FLAG: --image-tag="v0.9.0-rc.0"
I1003 16:23:56.199450       1 log.go:172] FLAG: --kubeconfig=""
I1003 16:23:56.199467       1 log.go:172] FLAG: --log-flush-frequency="5s"
I1003 16:23:56.199486       1 log.go:172] FLAG: --log_backtrace_at=":0"
I1003 16:23:56.199500       1 log.go:172] FLAG: --log_dir=""
I1003 16:23:56.199519       1 log.go:172] FLAG: --logtostderr="true"
I1003 16:23:56.199577       1 log.go:172] FLAG: --profiling="true"
I1003 16:23:56.199598       1 log.go:172] FLAG: --qps="100"
I1003 16:23:56.199625       1 log.go:172] FLAG: --requestheader-allowed-names="[]"
I1003 16:23:56.199644       1 log.go:172] FLAG: --requestheader-client-ca-file=""
I1003 16:23:56.199665       1 log.go:172] FLAG: --requestheader-extra-headers-prefix="[x-remote-extra-]"
I1003 16:23:56.199697       1 log.go:172] FLAG: --requestheader-group-headers="[x-remote-group]"
I1003 16:23:56.199718       1 log.go:172] FLAG: --requestheader-username-headers="[x-remote-user]"
I1003 16:23:56.199738       1 log.go:172] FLAG: --resync-period="10m0s"
I1003 16:23:56.199756       1 log.go:172] FLAG: --scratch-dir="/tmp"
I1003 16:23:56.199776       1 log.go:172] FLAG: --secure-port="8443"
I1003 16:23:56.199794       1 log.go:172] FLAG: --service-name="stash-operator"
I1003 16:23:56.199813       1 log.go:172] FLAG: --stderrthreshold="0"
I1003 16:23:56.199832       1 log.go:172] FLAG: --tls-cert-file="/var/serving-cert/tls.crt"
I1003 16:23:56.199860       1 log.go:172] FLAG: --tls-cipher-suites="[]"
I1003 16:23:56.199879       1 log.go:172] FLAG: --tls-min-version=""
I1003 16:23:56.199924       1 log.go:172] FLAG: --tls-private-key-file="/var/serving-cert/tls.key"
I1003 16:23:56.199944       1 log.go:172] FLAG: --tls-sni-cert-key="[]"
I1003 16:23:56.199963       1 log.go:172] FLAG: --use-kubeapiserver-fqdn-for-aks="true"
I1003 16:23:56.199977       1 log.go:172] FLAG: --v="3"
I1003 16:23:56.199996       1 log.go:172] FLAG: --vmodule=""

kubectl get all -n stash
NAME                                 READY   STATUS             RESTARTS   AGE
pod/stash-operator-94b6cbf66-n7pxl   1/2     CrashLoopBackOff   7          13m

NAME                     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/stash-operator   ClusterIP   10.43.18.118   <none>        443/TCP,56789/TCP   13m

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/stash-operator   0/1     1            0           13m

NAME                                       DESIRED   CURRENT   READY   AGE
replicaset.apps/stash-operator-94b6cbf66   1         1         0       13m

These are the events:
Events:
  Type     Reason     Age                     From                     Message
  ----     ------     ----                    ----                     -------
  Normal   Scheduled  14m                     default-scheduler        Successfully assigned stash/stash-operator-94b6cbf66-n7pxl to xxx-jenk-16
  Normal   Pulling    14m                     kubelet, xxx-jenk-16  Pulling image "combined-registry.sbx.zone/appscode/stash:v0.9.0-rc.0"
  Normal   Pulled     14m                     kubelet, xxx-jenk-16  Successfully pulled image "combined-registry.sbx.zone/appscode/stash:v0.9.0-rc.0"
  Normal   Pulling    14m                     kubelet, xxx-jenk-16  Pulling image "prom/pushgateway:v0.5.2"
  Normal   Pulled     14m                     kubelet, xxx-jenk-16  Successfully pulled image "prom/pushgateway:v0.5.2"
  Normal   Created    14m                     kubelet, xxx-jenk-16  Created container pushgateway
  Normal   Started    14m                     kubelet, xxx-jenk-16  Started container pushgateway
  Normal   Killing    13m                     kubelet, xxx-jenk-16  Container operator failed liveness probe, will be restarted
  Normal   Pulled     13m                     kubelet, xxx-jenk-16  Container image "combined-registry.sbx.zone/appscode/stash:v0.9.0-rc.0" already present on machine
  Normal   Created    13m (x2 over 14m)       kubelet, xxx-jenk-16  Created container operator
  Normal   Started    13m (x2 over 14m)       kubelet, xxx-jenk-16  Started container operator
  Warning  Unhealthy  13m (x5 over 14m)       kubelet, xxx-jenk-16  Liveness probe failed: Get https://10.42.2.202:8443/healthz: dial tcp 10.42.2.202:8443: connect: connection refused
  Warning  Unhealthy  9m28s (x26 over 14m)    kubelet, xxx-jenk-16  Readiness probe failed: Get https://10.42.2.202:8443/healthz: dial tcp 10.42.2.202:8443: connect: connection refused
  Warning  BackOff    4m27s (x16 over 8m22s)  kubelet, xxx-jenk-16  Back-off restarting failed container

**Comment by DineshC001** [comment]
logs from pushgateway container 
time="2019-10-03T17:02:10Z" level=info msg="Starting pushgateway (version=0.5.2, branch=HEAD, revision=231071b3e0a57b58df717bba5f4e5d88cac95389)" source="main.go:67"
time="2019-10-03T17:02:10Z" level=info msg="Build context (go=go1.10.3, user=root@c95e387ff56a, date=20180615-16:11:56)" source="main.go:68"
time="2019-10-03T17:02:10Z" level=info msg="Listening on :56789." source="main.go:124"

**Comment by hossainemruz** [comment]
@DineshC001 Can you please try Stash `0.9.0-rc.2`?

**Comment by jaygridley** [comment]
I have the same issue in our environment.

Kubernetes: 1.14.8
Cloud: Azure AKS
Deployment: Helm
Helm Chart Version: v0.9.0-rc.2

Workaround is to disable health checks via `apiserver.healthcheck.enabled: false`

**Comment by hossainemruz** [comment]
Try with latest version. If you still face the problem, feel free to reopen.
