### ISSUE TITLE
Support installation of the kubectl plugin via krew

### ISSUE THREAD

**Issue by AndrewSav** [stashed/stash#948]
It would be nice if stash kubectl plugin was available via [krew](https://github.com/kubernetes-sigs/krew-index#submitting-new-plugins)

**Comment by hossainemruz** [comment]
Hi @AndrewSav we would like to add it in `krew`. It's early day for the plugin and it is under heavy development. Once we have implemented the basic features, we would go forward to adding in krew.

**Comment by hossainemruz** [comment]
Done already. 
Ref: https://stash.run/docs/v2021.03.17/setup/install/kubectl_plugin/
