### ISSUE TITLE
feature-request: more annotations for auto-backups

### ISSUE THREAD

**Issue by cwrau** [stashed/stash#958]
Currently the only annotations used by the `BackupBlueprint` are:

```
stash.appscode.com/backup-blueprint
stash.appscode.com/target-paths
stash.appscode.com/volume-mounts
```

This means, that if we have two backups with a different schedule we have to create a new `BackupBlueprint`.

More annotations that fill this configuration gap, like for example:

```
stash.appscode.com/backup-schedule
```

And maybe more, that I didnt' think of 😄

**Comment by hossainemruz** [comment]
Sounds good to me.

**Comment by tamalsaha** [comment]
@cwrau , why not create another blueprint? Will it not give more visbility into this? 

Or, update the BackupConfiguration after it is created. We don't resync BackupConfiguration from Blueprint after the backupConfiguration is created. So, you should get the same result.

I am afraid that eventually all the fields will show up in annotations if we keep doing so. Passing spec via annotations are considered an anti-pattern in Kubernetes.

**Comment by cwrau** [comment]
We're using GitOps, where all our configuration is in a git repo, so updating the configuration afterwards is not an option.

How would you propose we set that up, without having to duplicate lots of configuration?

If we want to backup with three different schedules, we'd have to duplicate all but one line of YAML three times.

**Comment by hossainemruz** [comment]
I think it is reasonable to specifying schedule via an annotation. We are going to support it.
