### ISSUE TITLE
Possibility of restaure a subset of files

### ISSUE THREAD

**Issue by ahmedjami** [stashed/stash#965]
Hello,
I want to know if Stash offers the possibility to restore a subset of files.
Considering a Volume that is backup by Stash and which contains 5 directories, there is an option which allows restoring only 1 directory?
I see that this option exists with restic
https://restic.readthedocs.io/en/latest/050_restore.html
restic -r /srv/restic-repo restore 79766175 --target /tmp/restore-work --include /work/foo
Thanks.

**Comment by hossainemruz** [comment]
Not yet.

**Comment by ahmedjami** [comment]
Thanks @hossainemruz 
Are you planning to implement it ?

**Comment by hossainemruz** [comment]
Not planned yet. If we have enough user request, we may consider adding it.

**Comment by hossainemruz** [comment]
You can keep it open so we can revisit this feature request.

**Comment by hossainemruz** [comment]
Already added in the latest releases.
Ref: https://github.com/stashed/stash/issues/1262
