### ISSUE TITLE
Backup an annotated pod

### ISSUE THREAD

**Issue by ahmedjami** [stashed/stash#982]
Hi,

I want to know if it's possible to configure Stash to work with annotations like Velero:
_The first step is to add annotations to each of the Pods in the StatefulSet to indicate that the contents of the persistent volumes, mounted on cassandra-data, needs to be backed up as well._ 
`kubectl -n cassandra annotate pod/cassandra-0 backup.velero.io/backup-volumes=cassandra-data
pod/cassandra-0 annotated`

Thanks

**Comment by hossainemruz** [comment]
You mean this?
https://appscode.com/products/stash/v0.9.0-rc.2/guides/latest/auto-backup/overview/

**Comment by ahmedjami** [comment]
Yes ;)
Thanks a lot @hossainemruz
