### ISSUE TITLE
Postgres 12 support for stash-postgres

### ISSUE THREAD

**Issue by ljani** [stashed/stash#989]
I'm planning to update my Postgres instance to version 12.1. However, it seems [`stash-postgres` does not have a `release-12.1` branch](https://github.com/stashed/postgres/branches). I guess I should postpone my update operation, if I want to use `stash-postgres`.

[Postgres 12 was released on 2019-10-03.](https://www.postgresql.org/about/news/1976/)

**Comment by k0da** [comment]
Is there any blocker releasing postgres 12?

**Comment by cbouissoncs** [comment]
Does the roadmap include PostgreSQL 12 ?

**Comment by hossainemruz** [comment]
Already added.
